### PR TITLE
Do not overwrite specific wails versions

### PR DESCRIPTION
**Pull request by OlegGulevskyy**
This PR fixes the issue raised in #2057 , where comparing versions of `wails` package installed via a specific commit `go get github.com/wailsapp/wails/v2@928...` was detected as **out of date** version and was overwritten all the time.

Adding very simple logic to check if a version contains something else apart from the correct semver, it means the developer knows what they are doing, so we should let things as they are.

Not sure if this is the best way to detect this though, I quickly looked over `semver` package to see if they have a method detecting stuff apart from the actual version, but didn't find any.

Happy to get better ideas from you awesome people!

### CODE REVIEW

**Comment by mholt** [comment]
Oh nice. I'll leave it up to the maintainers to decide the best approach (of course) but from my own perspective I think that's logical: if I'm not using a tagged release, it's probably intentional.

Either that, or the logic needs to be smarter to "go get" the specific version the binary is running. But then it changes my go.mod which I might not want.

So, personally, I think this approach is good. :man_shrugging: 

Thanks! :D

**Comment by leaanthony** [comment]
Thanks @OlegGulevskyy ! Historically we've used `vX.X.X-beta.YY` which may get picked up by this. We're some way off v3 beta so I'm not that concerned about it right now but might be worth thinking about.

**Comment by OlegGulevskyy** [comment]
Sure, that's a good point! If that's a potential in future again, then we should probably figure out a smarter handling for this.
Maybe like first check for words beta, alpha etc ? Feels a bit Jacky though. I wonder if semver does not offer this kind of checks for beta alpha versions etc.

Thanks for feedback guys!

**Comment by leaanthony** [comment]
I was sure semver library allowed you to extract the metadata part of the version

**Comment by OlegGulevskyy** [comment]
Got it, I am not familiar with it, so I will follow up on this

Thanks!

**Comment by mholt** [comment]
You probably want https://pkg.go.dev/github.com/Masterminds/semver/v3#Version.Prerelease and possibly https://pkg.go.dev/github.com/Masterminds/semver/v3#Version.Metadata

**Comment by leaanthony** [comment]
@OlegGulevskyy - shall we convert this to draft?

**Comment by OlegGulevskyy** [comment]
My bad, I completely forgot about this PR!
Thanks for bumping it up. I will look into it by the end of the week max, so with that in mind if you feel like it should be in Draft stage then let's convert it

**Comment by OlegGulevskyy** [comment]
My bad, I completely forgot about this PR!
Thanks for bumping it up. I will look into it by the end of the week max, so with that in mind if you feel like it should be in Draft stage then let's convert it

**Comment by leaanthony** [comment]
Yeah if @mholt is happy with this behaviour I think it's good to go. Good job!

**Comment by mholt** [comment]
I will test it today :)

**Comment by mholt** [comment]
Hmm, when I try this patch, I still get the error from when I tried other non-released versions after 2.2:

```
ERROR: 
flag provided but not defined: -tsprefix
Usage of /tmp/wailsbindings:
  -config string
        path to the configuration file (default "/home/matt/.config/timelinize/timelinize.json")
  -gui
        run GUI (default true)
  -server
        run HTTP server
```

I think it's unrelated to the go.mod stuff, but it means I can't test this patch until I figure out why this is happening.

I don't know enough about Wails' internals yet to know when/why this is happening, but it looks like Wails is compiling a binary called `/tmp/wailsbindings` that happens to be my program's `main.go`; because my `main.go` is what defines these flags. Apparently Wails is trying to run my binary but is passing `-tsprefix`, which I believe is a new flag on the Wails binary.

So it seems like Wails is trying to run a binary that should know what `-tsprefix` is, but it's running mine instead.

Is that intended? :thinking:

**Comment by OlegGulevskyy** [comment]
Thanks for testing it @mholt 
What was the issue with -tsprefix in the end?

**Comment by mholt** [comment]
@OlegGulevskyy It's unrelated to this, but basically, if your app calls `flag.Parse()` then it breaks the latest yet-unreleased versions of Wails, which adds flags to your program. I think @stffabi said he'd make a PR that changes it to env vars instead of messing with flags, which sounds much better!

**Comment by mholt** [comment]
Anyway, to clarify, this patch LGTM and could be taken out of "draft mode" IMO.

**Comment by mholt** [comment]
Cool :) Thank you!

**Pull request merged**
