### PR TITLE
Add Russian README.md

### PR DESCRIPTION
**Pull request by MIMBOL228**
# Description

Addition of readme file in Russian language.

### CODE REVIEW

**Comment by MIMBOL228** [comment]
Additionally, I would like to ask you to approve my application to join the translation team on Crowdin (username: mimbol).

**Comment by leaanthony** [comment]
There's been a Portuguese readme added. Any chance you could fix the merge conflicts and add the Russian readme link to the Portuguese readme too? Thank you 🙏

**Comment by leaanthony** [comment]
@OlegGulevskyy is the best person to ask about Crowdin right now 👍

**Comment by OlegGulevskyy** [comment]
I don't think I can approve memberships, managers perms are on you @leaanthony

**Comment by MIMBOL228** [comment]
All conflicts are resolved. I will be glad to be accepted into the translation team on Chowdin and to resolve the merger request.

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Thanks for taking the time to do this 🙏

**Comment by MIMBOL228** [comment]
You are welcome. Can I ask you to approve my request to join in team on Chowdin?

**Pull request merged**
