### PR TITLE
[v3 alpha] Fix drag-n-drop on some linux distros

### PR DESCRIPTION
**Pull request by abichinger**
# Description

On some linux distributions the cursor gets stuck when moving files over the drag-n-drop example. I haven't figured out why only some distributions are affected.

Fixes https://discord.com/channels/1042734330029547630/1220475512833441802

Changes:
- enable dnd for `w.vbox` instead of `w.webview`
- disable `w.webview` as a dnd destination with `gtk_drag_dest_unset`
  This results in events like [`drop`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/drop_event) and `dragover` to not fire at all
- Refactor: move C code

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

By running the drag-n-drop example.

Because not all distributions are affected by the error, I also created a Dockerfile to reproduce the error.

```Dockerfile
FROM x11docker/gnome

RUN apt update -y -q
RUN DEBIAN_FRONTEND=noninteractive apt install -y curl git build-essential libgtk-3-dev libwebkit2gtk-4.0-dev pkg-config

RUN curl -s https://dl.google.com/go/go1.22.1.linux-amd64.tar.gz | tar -v -C /usr/local -xz
ENV PATH $PATH:/usr/local/go/bin

WORKDIR /
RUN git clone -b v3-alpha https://github.com/wailsapp/wails.git

WORKDIR /wails/v3/examples/drag-n-drop
RUN go mod tidy
RUN go build .
RUN cp ./drag-n-drop /

CMD gnome-shell
```

The docker image can be run with [x11docker](https://github.com/mviereck/x11docker).

```shell
docker build -t drag-n-drop -f Dockerfile .
docker pull x11docker/xserver
x11docker --desktop --xc=yes --init=systemd drag-n-drop
```

- [ ] Windows
- [ ] macOS
- [x] Linux
  
## Test Configuration

```shell
# Build Environment
Wails CLI    | v3.0.0-alpha.3                          
Go Version   | go1.22.0                                
Revision     | 33946a7aace91ffb1a3992dcf3af7a2071ac70d2
Modified     | true                                    
-buildmode   | exe                                     
-compiler    | gc                                      
CGO_CFLAGS   |                                         
CGO_CPPFLAGS |                                         
CGO_CXXFLAGS |                                         
CGO_ENABLED  | 1                                       
CGO_LDFLAGS  |                                         
GOAMD64      | v1                                      
GOARCH       | amd64                                   
GOOS         | linux                                   
vcs          | git                                     
vcs.modified | true                                    
vcs.revision | 33946a7aace91ffb1a3992dcf3af7a2071ac70d2
vcs.time     | 2024-03-19T10:56:54Z                    

# System
Name         | Manjaro Linux                                                                                                 
Version      | Unknown                                                                                                       
ID           | manjaro                                                                                                       
Branding     |                                                                                                               
Platform     | linux                                                                                                         
Architecture | amd64                                                                                                         
gcc          | 13.2.1-5                                                                                                      
libgtk-3     | 1:3.24.41-1                                                                                                   
libwebkit    | 2.42.5-2                                                                                                      
npm          | 10.5.0-1                                                                                                      
pkg-config   | 2.1.0-2                                                                                                       
CPU          | AMD Ryzen 5 3600 6-Core Processor                                                                             
GPU 1        | Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] (Advanced Micro Devices, Inc. [AMD/ATI]) - Driver: amdgpu 
Memory       | 32GB                                                                                                          

# Diagnosis
 SUCCESS  Your system is ready for Wails development!
```

# Checklist:

- [x] I have updated `mkdocs-website/docs/changelog.md` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tmclane — CHANGES_REQUESTED** [review]
Can you tell me why we need to split out to the linux_cgo.h file? 
There is only one file that includes it now.  I don't see why that is necessary.

Will you put it back unless there is a good reason I am missing?

**Comment by abichinger** [comment]
I did it for syntax highlighting and IntelliSense. I'm happy to undo it if that's not reason enough.

**Comment by tmclane** [comment]
Let's leave it split out.  Indentation is hard enough in a comment already.  

FYI I couldn't get the docker image to work properly for some reason.  Will try again today.

**Review by tmclane — APPROVED** [review]
I'm rescinding my request to put the code back inside the `linux_cgo.go` file at this time.
Doesn't seem to cause any harm.

**Comment by tmclane** [comment]
It turns out that the `linux_cgo.c` file is not acceptable.  It causes `go test` errors actually.

Please put the relevant code back in to the relevant sections of `linux_cgo.go` and remove the new `linux_cgo.h` and `linux_cgo.c` files.

**Comment by abichinger** [comment]
> It turns out that the linux_cgo.c file is not acceptable. It causes go test errors actually.

Whoops, didn't notice that. I moved the code back into `linux_cgo.go`

**Comment by tmclane** [comment]
Thank you!

**Pull request merged**
