### PR TITLE
Update templates.mdx

### PR DESCRIPTION
**Pull request by xijaja**
添加 solid 模版的中文描述信息。

### CODE REVIEW

**Review by steowens — APPROVED** [review]
[The]([url](Translation)) 
change looks good. Verified the translation via Google Translate.

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Could we add these templates to the English docs too?

**Comment by leaanthony** [comment]
Thanks @xijaja 👍

**Comment by xijaja** [comment]
I've added English versions of these templates earlier. Now there might be some issues making it impossible to see them in the wails' website.

**Pull request merged**
