### PR TITLE
Feature/vite v3

### PR DESCRIPTION
**Pull request by leaanthony**
Updated template
Run frontend install if node_modules does not exist (or else vite won't run!).

### CODE REVIEW

**Comment by leaanthony** [comment]
@stffabi - I'm getting an interesting error that I've never seen before:

```
DEB | [ExternalAssetHandler] Loading 'http://127.0.0.1:5173/'
echo: http: panic serving 127.0.0.1:54213: interface conversion: *httptest.ResponseRecorder is not http.Hijacker: missing method Hijack
goroutine 83 [running]:
net/http.(*conn).serve.func1()
        /Users/leaanthony/go/go1.18.1/src/net/http/server.go:1825 +0xb0
panic({0x102d421a0, 0x140002a0b70})
        /Users/leaanthony/go/go1.18.1/src/runtime/panic.go:844 +0x258
github.com/labstack/echo/v4.(*Response).Hijack(0x140000a2970?)
        /Users/leaanthony/go/pkg/mod/github.com/labstack/echo/v4@v4.7.2/response.go:94 +0x34
net/http/httputil.(*ReverseProxy).handleUpgradeResponse(0x140000a6000, {0x102db2a40, 0x1400008ee40}, 0x140000ecc00, 0x140002be5a0)
        /Users/leaanthony/go/go1.18.1/src/net/http/httputil/reverseproxy.go:590 +0x470
net/http/httputil.(*ReverseProxy).ServeHTTP(0x140000a6000, {0x102db2a40?, 0x1400008ee40}, 0x140000ecb00)
        /Users/leaanthony/go/go1.18.1/src/net/http/httputil/reverseproxy.go:310 +0x7e0
github.com/wailsapp/wails/v2/internal/frontend/devserver.newExternalDevServerAssetHandler.func4({0x102db45d8, 0x140000da3c0})
        /Users/leaanthony/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/devserver/external.go:65 +0xc0
github.com/labstack/echo/v4.(*Echo).add.func1({0x102db45d8, 0x140000da3c0})
        /Users/leaanthony/go/pkg/mod/github.com/labstack/echo/v4@v4.7.2/echo.go:520 +0x54
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0x140000b6000, {0x102db2e00?, 0x140000c0a40}, 0x140000ecb00)
        /Users/leaanthony/go/pkg/mod/github.com/labstack/echo/v4@v4.7.2/echo.go:630 +0x3ec
github.com/wailsapp/wails/v2/internal/frontend/assetserver.(*AssetServer).ServeHTTP(0x140000c0180, {0x102db2a40, 0x1400008ede0}, 0x140000ecb00)
        /Users/leaanthony/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/assetserver/assetserver.go:76 +0x234
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run.func3({0x102db45d8, 0x140000da320})
        /Users/leaanthony/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.38/internal/frontend/devserver/devserver.go:110 +0x64
github.com/labstack/echo/v4.(*Echo).add.func1({0x102db45d8, 0x140000da320})
        /Users/leaanthony/go/pkg/mod/github.com/labstack/echo/v4@v4.7.2/echo.go:520 +0x54
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0x1400019d200, {0x102db2dd0?, 0x140000ac460}, 0x140000ecb00)
        /Users/leaanthony/go/pkg/mod/github.com/labstack/echo/v4@v4.7.2/echo.go:630 +0x3ec
net/http.serverHandler.ServeHTTP({0x1400009b8c0?}, {0x102db2dd0, 0x140000ac460}, 0x140000ecb00)
        /Users/leaanthony/go/go1.18.1/src/net/http/server.go:2916 +0x3fc
net/http.(*conn).serve(0x140000da280, {0x102db30b8, 0x140002a0270})
        /Users/leaanthony/go/go1.18.1/src/net/http/server.go:1966 +0x56c
created by net/http.(*Server).Serve
        /Users/leaanthony/go/go1.18.1/src/net/http/server.go:3071 +0x450
```

I'm not sure how the changes are causing this. Any ideas? I tracked this down in the Caddy repo: https://github.com/caddyserver/caddy/issues/133

**Comment by stffabi** [comment]
That's very interesting, it seems like the index request to `http://127.0.0.1:5173/` is a websocket and not a normal GET request. Since we inject the bindings we record the original request, transform the html file and rewrite it. So we have not the possibility to hijack the TCP connection there.
Is that the new vite default port on `5173`? Do you see a `101 - switching protocols` when browsing to `http://127.0.0.1:5173/` with your browser?

**Comment by leaanthony** [comment]
I didn't look at the network tab at the time. Interesting it still works 🤔

**Comment by stffabi** [comment]
Seems like they have changed how vite3 creates the websocket, AFAIK until now that wasn't requested on the root but in a folder. So it seems we need some adjustments for vite3, will try to take a look into it during the next days.

**Comment by stffabi** [comment]
@leaanthony I've added a commit which should add support for vite-3. Would it be possible for you to test it?

**Comment by leaanthony** [comment]
This works well for me. I've update the devserver url detector as it was failing to find it as `Local:` had ANSI codes.

**Comment by leaanthony** [comment]
I'm not quite sure why this PR is so big and contains things other than intended. I will probably create a new branch from master and cherry pick the relevant changes.

**Comment by AlexBitsTech** [comment]
Hello, 
Having the exact same problem as @ianmjones , I also pulled the PR to test if it fixes the problem. 
I can confirm it is working for me no problem on Windows 11. If you need any more debug info, do not hesitate.

**Comment by leaanthony** [comment]
Updating the templates is pretty time consuming. I could get a svelte only patch in.

**Comment by leaanthony** [comment]
Closing this to make a svelte specific PR

**Pull request closed without merging**
