### PR TITLE
Use scaling when setting min/max window

### PR DESCRIPTION
**Pull request by leaanthony**
Scaling is only considered when setting the window to fullscreen. This PR considers the scale when setting min/max width/height.

Potential fix for #1517.

### CODE REVIEW

**Comment by acheong08** [comment]
This seems to be stable, when will it be merged?

**Comment by leaanthony** [comment]
Waiting for @skamensky to confirm about appoptions Fullscreen: https://github.com/wailsapp/wails/issues/1517#issuecomment-1186135498

**Comment by leaanthony** [comment]
@skamensky happy for this to be merged?

**Comment by skamensky** [comment]
From my I've seen it's a partial fix without any regressesions. I'll check layer today to see if there's something I can do to make it a complete fix. But if not, I see no reason not to merge it.

**Comment by leaanthony** [comment]
It was a full fix on my system. Startup options worked as expected

**Pull request merged**
