### PR TITLE
update go minimum version

### PR DESCRIPTION
**Pull request by lmb1113**
V2.7.1 Go 1.20 is now the minimum supported Go version.

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change
  
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [ ] Windows
- [ ] macOS
- [ ] Linux
  
## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [ ] My code follows the general coding style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Documentation**
	- Updated the installation guide to reflect the new requirements for Go and Node versions for Wails installation.
	- Increased the minimum required Go version from 1.18 to 1.20.
	- Adjusted the minimum required Node version from 15 to 15+.

### CODE REVIEW

**Comment by lmb1113** [comment]
> 谢谢您，您是否也可以在这里更新构建约束`/v2/internal/goversion/`？那就太棒了🙏



> Thanks for this, would it be also possible for you to update the build constraints here`/v2/internal/goversion/` ? That would be awesome 🙏

Very honored

**Comment by leaanthony** [comment]
Thanks for this! I see you've updated the docs for v2.8, which will eventually be deleted. Would;d it be possible to update `website/docs/gettingstarted/installation.mdx` instead? This would allow us to keep the change moving forward 🙏

**Comment by lmb1113** [comment]
> Thanks for this! I see you've updated the docs for v2.8, which will eventually be deleted. Would it be possible to update `website/docs/gettingstarted/installation.mdx` instead? This would allow us to keep the change moving forward 🙏

ok

**Comment by leaanthony** [comment]
Thanks 🙏 Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

**Comment by lmb1113** [comment]
> Thanks 🙏 Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

It already exists.

**Comment by leaanthony** [comment]
The PR contains an update to a versioned doc. We will lose that eventually 👍

**Review by leaanthony — APPROVED** [review]

**Pull request merged**
