### PR TITLE
elementary support and other fixes

### LINKED ISSUE #193: Support Distribution 'elementary'
**Description**
Distribution 'elementary' is currently unsupported.

**Further Information**

| Name   | Value |
| ----- | ----- |
| Wails Version | v0.17.0 |
| Go Version    | go1.12.7 |
| Platform      | linux |
| Arch          | amd64 |
| GO111MODULE   | (Not Set) |
| Distribution ID   | elementary |
| Distribution Version   | 5.0 |
| Discovered by   | lsb |

*Please add any extra information here, EG: libraries that are needed to make the distribution work, or commands to install them*

### PR DESCRIPTION
**Pull request by bh90210**
#193 #187

### CODE REVIEW

**Comment by bh90210** [comment]
at the moment opensuse crashes with 
```
16c99ae698d7:/ # cd wails/cmd/wails && go install && wails setup                                                                                                                  
 _       __      _ __    
| |     / /___ _(_) /____                                                                                                                                                          
| | /| / / __ `/ / / ___/                                                                                                                                                          
| |/ |/ / /_/ / / (__  )  v0.17.12-pre
|__/|__/\__,_/_/_/____/   https://wails.app
The lightweight framework for web-like apps

What is your name (ret): 
What is your email address (sdfs@sdfs.rge): 

Wails config saved to: /root/.wails/wails.json
Feel free to customise these settings.

Detected Platform: Linux
Checking for prerequisites...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x77cacb]

goroutine 1 [running]:
github.com/wailsapp/wails/cmd.(*Distribution).GetRelease(...)
        /wails/cmd/linuxdb.go:25
github.com/wailsapp/wails/cmd.getRequiredProgramsLinux(0x0)
        /wails/cmd/prerequisites.go:47 +0xdb
github.com/wailsapp/wails/cmd.GetRequiredPrograms(0x0, 0xc0000f9d78, 0x77a87e)
        /wails/cmd/prerequisites.go:26 +0x22
main.checkRequiredPrograms(0xc000017020, 0x86a375, 0x1d)
        /wails/cmd/wails/0_setup.go:152 +0x34
main.init.0.func1(0xc0000f9ea8, 0x4136a3)
        /wails/cmd/wails/0_setup.go:45 +0xfa
github.com/wailsapp/wails/cmd.(*Command).Run(0xc000090420, 0xc00000e0b0, 0x0, 0x0, 0xc000081198, 0x26)
        /wails/cmd/cli.go:170 +0xd0
github.com/wailsapp/wails/cmd.(*Command).Run(0xc000090370, 0xc00000e0b0, 0x1, 0x1, 0xc0000f9f78, 0x788caf)
        /wails/cmd/cli.go:150 +0x2d5
github.com/wailsapp/wails/cmd.(*Cli).Run(0xc00000e7a0, 0x0, 0x0, 0x0, 0xc0000f9f88, 0xc00006e058)
        /wails/cmd/cli.go:47 +0x8e
main.main()
        /wails/cmd/wails/main.go:15 +0x3e
16c99ae698d7:/wails/cmd/wails # cat /etc/os-release
NAME="openSUSE Leap"
VERSION="15.1 "
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.1"
PRETTY_NAME="openSUSE Leap 15.1"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

**Comment by bh90210** [comment]
I got it this far. it almost alright.
on ubuntu `wails setup` runs fines
```
Detected Platform: Linux
Checking for prerequisites...
Program 'gcc' found: /usr/bin/gcc
Program 'pkg-config' found: /usr/bin/pkg-config
Program 'npm' found: /usr/bin/npm
Library 'libgtk-3-dev' installed.
Library 'libwebkit2gtk-4.0-dev' installed.

🚀 Ready for take off!
Create your first project by running 'wails init'.
``` 

on opensuse and arch I get this now 
```
Detected Platform: Linux
Checking for prerequisites...

🚀 Ready for take off!
Create your first project by running 'wails init'.
```

**Comment by leaanthony** [comment]
Is this pr still valid based on your last message?

**Comment by bh90210** [comment]
I'm closing this. I am going to work the `err == nil` bug fix.
I suggest to drop suse for now (uninformed decision of mine..)

**Pull request closed without merging**
