### PR TITLE
ja translation of tutorials

### PR DESCRIPTION
**Pull request by Watson-Sei**
Change:
- A Japanese translation of the v2.3.1 documentation tutorial has been prepared.

### CODE REVIEW

**Review by leaanthony — CHANGES_REQUESTED** [review]
Thank you so much for doing this 🙏 Could you please move these files to the `current` directory rather than v2.3.1? This will ensure they don't get wiped out in the future. Thank you 🙏

**Comment by Watson-Sei** [comment]
Oops, maybe the translation should have been done by crowdin.com?

**Comment by leaanthony** [comment]
It should be ok as the files should sync back

**Review by Watson-Sei — COMMENTED** [review]
LGTM

**Comment by leaanthony** [comment]
These failed are still in the v2.3.1 directory. If you move them to current, I can merge 👍

**Review by leaanthony — APPROVED** [review]

**Pull request merged**
