### PR TITLE
add support for 'DomReady' callback on linux

### PR DESCRIPTION
**Pull request by napalu**
cosmetic: use bodyLen instead of len() in processRequest()

### CODE REVIEW

**Comment by napalu** [comment]
A small nitpick: the term "DomReady" is in my opinion misleading because it suggests and equivalence to javascript's 'DOMContentLoaded' whereas 'DomReady' is emitted when navigation has finished loading. Maybe the description and name of the go callback should be changed to reflect this?

**Comment by napalu** [comment]
fixes #1246

**Comment by leaanthony** [comment]
> A small nitpick: the term "DomReady" is in my opinion misleading because it suggests an equivalence to javascript's 'DOMContentLoaded' whereas 'DomReady' is emitted when navigation has finished loading. Maybe the description and name of the go callback should be changed to reflect this?

That's a valid point. Originally it was to indicate that elements of the page were ready, including the runtime but I agree the name is now misleading. What would you call it?

**Comment by napalu** [comment]
Something like `resourcesLoaded` might be more appropriate - currently the  comment to describe `domReady` after `wails init` is run reads: `domReady is called after the front-end dom has been loaded`.

I suppose we could leave the name as-is and just alter the comment to read `domReady` is called after front-end resources have been loaded` - what do you think?

**Comment by leaanthony** [comment]
Updated comments in templates + website. Thanks for all your contributions 🙏

**Pull request merged**
