### PR TITLE
fix: parse struct references for type generation

### LINKED ISSUE #2489: [v2] Binding missing types after upgrading to v2.4.0
### Description

When using v2.3.1, bindings were generated to include the types. However, v2.4.0 somehow breaks that:

```diff
diff --git a/frontend/wailsjs/go/models.ts b/frontend/wailsjs/go/models.ts
index e57b763..edcb27f 100755
--- a/frontend/wailsjs/go/models.ts
+++ b/frontend/wailsjs/go/models.ts
@@ -201,9 +201,9 @@ export namespace phantom {
 export namespace rtt {

        export class Statistics {
-           // Go type: time.Time
+           // Go type: time
            since: any;
-           // Go type: time.Time
+           // Go type: time
            until: any;
            min: number;
            average: number;
diff --git a/frontend/wailsjs/go/phantom/Application.d.ts b/frontend/wailsjs/go/phantom/Application.d.ts
index 30e33c4..e536e41 100755
--- a/frontend/wailsjs/go/phantom/Application.d.ts
+++ b/frontend/wailsjs/go/phantom/Application.d.ts
@@ -15,11 +15,11 @@ export function GetConnectedForwarderNodes():Promise<Array<phantom.ForwarderNode

 export function GetConnectedTunnelNodes():Promise<Array<phantom.TunnelNode>>;

-export function GetPhantomConfig():Promise<phantom.PhantomConfig>;
+export function GetPhantomConfig():Promise<any>;

 export function GetRegisteredHostnames():Promise<Array<string>>;

-export function GetSpecterConfig():Promise<client.Config>;
+export function GetSpecterConfig():Promise<any>;

 export function RebuildTunnels(arg1:Array<client.Tunnel>):Promise<void>;

@@ -49,4 +49,4 @@ export function UpdateApex(arg1:string):Promise<void>;

 export function UpdateForwaderLabel(arg1:number,arg2:string):Promise<void>;

-export function UpdatePhantomConfig(arg1:phantom.PhantomConfig):Promise<void>;
+export function UpdatePhantomConfig(arg1:any):Promise<void>;
```

### To Reproduce

Run `wails dev` on two branches:

v2.3.1: https://github.com/zllovesuki/phantom/tree/main
v2.4.0: https://github.com/zllovesuki/phantom/tree/next

### Expected behaviour

Correct bindings to be generated

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
PS D:\Vendetta\code\phantom> wails doctor
DEB | Using go webview2loader
Wails CLI v2.4.0

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 19044)
ID           | 21H2
Go Version   | go1.20.1
Platform     | windows
Architecture | amd64

# Wails

Version | v2.4.0

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 110.0.1587.69
npm        | N/A          | Installed | 9.3.1
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dominictwlee**
this should fix the issues in v2.4.0 where reference type structs were breaking return types in Typescript. I think the issue stems from valueType capturing what should've been part of the valuePackage group because of  ".+". 

This should remedy the concerns raised in #2490 around stripping the asterix. In case we need it in the future, we could capture the asterix in a new group. I've added it to the non-capturing group for now.

@OlegGulevskyy @leaanthony let me know what you think.

I've also added a few additional cases to cover promise bindings.

closes #2489

### CODE REVIEW

**Comment by dominictwlee** [comment]
@leaanthony bump, just following up on this to get a review, thanks!

**Comment by zllovesuki** [comment]
👍 this looks way better

**Comment by dominictwlee** [comment]
https://github.com/dominictwlee/test-ts-gen

@zllovesuki minimal example. clone my fork, uncomment go.mod replace to local wails dir and you're good to go.

**Review by leaanthony — APPROVED** [review]

**Comment by dominictwlee** [comment]
@leaanthony thanks for the review. Anything else you need from me to get this merged in?

**Comment by AlbinoDrought** [comment]
I was updating from 2.3.1 to 2.4.1 to fix the CreateWebResourceResponse issue and experienced this `Promise<any>` issue, I can confirm this PR fixes it for me 🎊

**Comment by leaanthony** [comment]
Thanks for this @dominictwlee. It would be good if you could update `changelog.mdx` under the website directory with your changes 👍

**Pull request merged**
