### PR TITLE
[v3] Added AppDataDirectory path

### PR DESCRIPTION
**Pull request by ansxuman**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #3811 

## Type of change
  
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [ ] Windows
- [x] macOS
- [ ] Linux
  
## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Introduced new methods for retrieving user-specific paths for application data, cache, and configuration across macOS, Linux, and Windows.
	- Added a new `Path` method in the application package for enhanced path management.
	- Included templates for `sveltekit` and `sveltekit-ts` configured for non-SSR development.

- **Bug Fixes**
	- Fixed `AlwaysOnTop` functionality on macOS.
	- Resolved various issues related to drag-and-drop functionality, compile errors on Linux, and system tray startup panics on Windows.

- **Documentation**
	- Updated changelog to reflect notable changes and new features in the application API.

### CODE REVIEW

**Comment by ansxuman** [comment]
https://github.com/wailsapp/wails/discussions/3811

**Comment by leaanthony** [comment]
Hi @ansxuman - I think we should simply expose the XDG methods and exports via `app.Path` rather than wrapping the functionality and providing defaults if paths don't exist. I think we should leave that for the developer to decide. Thoughts?

**Comment by ansxuman** [comment]
> Hi @ansxuman - I think we should simply expose the XDG methods and exports via `app.Path` rather than wrapping the functionality and providing defaults if paths don't exist. I think we should leave that for the developer to decide. Thoughts?

Thats a good point, devs will have more control, i have made the changes.

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Refactored the PR (I hope you don't mind!) to make it easier to maintain. Thanks for kicking this off @ansxuman 🙏

**Comment by ansxuman** [comment]
> Refactored the PR (I hope you don't mind!) to make it easier to maintain. Thanks for kicking this off @ansxuman 🙏

My Pleasure

**Pull request merged**
