### PR TITLE
Support selecting multiple directories

### PR DESCRIPTION
**Pull request by mooijtech**
# Description

Adds support for selecting multiple folders/directories.

## Type of change
  
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [x] Linux
  
## Test Configuration

```bash
# Wails
Version         | v2.5.1                                  
Revision        | d5631afb01895d232e455f6e230fe147a74f625e
Modified        | true                                    
Package Manager | pacman                                  

# System
┌───────────────────────────┐
| OS           | Arch Linux |
| Version      | Unknown    |
| ID           | arch       |
| Go Version   | go1.20.2   |
| Platform     | linux      |
| Architecture | amd64      |
└───────────────────────────┘

# Dependencies
┌─────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version     |
| *docker    | docker       | Installed | 1:23.0.2-1  |
| gcc        | gcc          | Installed | 12.2.1-2    |
| libgtk-3   | gtk3         | Installed | 1:3.24.37-1 |
| libwebkit  | webkit2gtk   | Installed | 2.40.0-2    |
| npm        | npm          | Installed | 8.19.2-1    |
| pkg-config | pkgconf      | Installed | 1.8.1-1     |
└────────────── * - Optional Dependency ──────────────┘

```

# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mooijtech** [comment]
It would be nice to have these functions in the JavaScript runtime.

**Comment by leaanthony** [comment]
Thanks for opening this. Is your plan to also test mac / windows and update the runtime so this can be called from JS? Thanks 🙏

**Comment by mooijtech** [comment]
I will add all `dialog` functions to the JavaScript runtime and also test on Windows and (possibly) macOS.

**Comment by mooijtech** [comment]
I have tested this and it works on Linux, macOS and Windows (no selection, single directory selection while configured for multiple and of course multiple directory selection).
The JavaScript runtime now supports calling `dialog` functions which I have also tested.

I didn't expect adding this functionality to take as long as it did.
Feel free to review/request changes.

**Comment by mooijtech** [comment]
@leaanthony @stffabi Feel free to review/merge

**Comment by leaanthony** [comment]
It certainly does take a long time! Thanks for this. Will review soon 👍

**Comment by leaanthony** [comment]
Could you please provide a description of the change you've done and why you did it that way? I can see what's there, I just need to understand why you took that approach. Thanks 🙏

**Comment by mooijtech** [comment]
I thought a type switch would be the fastest route honestly, I tried to do it so that a `[]string` gets marshaled to a `string` but I don't think I could get it to work (double marshal, the final being in the `Callback`, I think it went to base64 first but that was because it was represented as `byte` not `string`), I could have maybe fixed that.
Using `systemcalls` already had the functionality I needed so I used that, it's possible to move this to another location.

Other than that, I don't know what I would have done differently.

**Comment by mooijtech** [comment]
While this code works, I'm working on something else at the moment.
Possibly have a final cleanup since it's been a while.

**Comment by mooijtech** [comment]
Closed in favor of https://github.com/wailsapp/wails/pull/2960

**Pull request closed without merging**
