### PR TITLE
feature: add runtime func WindowSetAlwaysOnTop

### PR DESCRIPTION
**Pull request by chenxiao1990**
This PR resolves feature request #1439.
Add windows 、linux platform WindowSetAlwaysOnTop function . 
Darwin platform no environment , Not implemented. 
JS runtime interface Not implemented.

### CODE REVIEW

**Review by leaanthony — COMMENTED** [review]
Thanks for opening this. A few things: 
  - there's already functions for top level windows that we call during startup so we should reuse those
  - It looks like the calls to set and unset the top window are the same
  - We'd need to add a JavaScript method for completeness
  - The docs will need updating with the new runtime method

It's a good start though! 👍

**Comment by chenxiao1990** [comment]
> Thanks for opening this. A few things:
> 
> * there's already functions for top level windows that we call during startup so we should reuse those
> * It looks like the calls to set and unset the top window are the same
> * We'd need to add a JavaScript method for completeness
> * The docs will need updating with the new runtime method
> 
> It's a good start though! 👍



add a JavaScript method for completeness
The docs updating with the new runtime method

**Comment by chenxiao1990** [comment]
Yes, i think a single api call WindowSetAlwaysOnTop(bool)  is a good idea.
I will modify it.

**Comment by leaanthony** [comment]
LGTM!

**Pull request merged**
