### PR TITLE
[v3] fix tests after plugins and event refactor

### PR DESCRIPTION
**Pull request by stendler**
# Description

Fix most of the tests failing since the recent refactorings for the plugin and event systems, as well as some other issues regarding method signatures and logging calls (https://github.com/wailsapp/wails/actions/runs/10837644078).

(Skipping the failing mac tests introduced in 6787ce9c40372749b95225dbcc902f91a5b613e6 as I don't have a mac, but the role `UseSelectionForFind` declared for darwin is not defined in roles.go)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
  
In CI: https://github.com/stendler/wails/actions/runs/10863138422

# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [ ] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Release Notes

- **New Features**
	- Streamlined event handling mechanism for "clicked", "button-pressed", and "hover" events.
	- Enhanced flexibility in service initialization with additional service options.

- **Improvements**
	- Simplified error logging during service startup for better consistency.
	- Improved readability and maintainability of event emission logic.
	- Enhanced clarity of plugin lifecycle methods and context-aware initialization.

- **Bug Fixes**
	- Resolved issues related to menu item management and event processing on macOS.
	- Fixed a system tray startup panic on Windows for smoother operation.

### CODE REVIEW

**Comment by leaanthony** [comment]
Thanks for taking the time to do this🙏 The v3 branch is considered unstable at the moment so it can sometimes be broken.

Please could you add an entry to the changelog located at `mkdocs-website/docs/changelog.md`? Thanks!

**Comment by stendler** [comment]
@leaanthony yeah, no worries - I expect it to be broken sometimes. The tests and CI are great to find easy targets to contribute a fix - especially if I try to keep the CI in my fork green anyway. :)
Also wasn't sure if fixing tests warrants an entry in the changelog - it's fixing something that was not even released yet. But having my contributions recognized in there is much appreciated!

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Not quite sure why github isn't picking p that this is merged on v3-alpha but it is 👍

**Comment by stendler** [comment]
I don't know how GitHub detects squashed merges, but maybe the squashed commit is differing too much (contents due to resolved conflicts, author, message..).
In any way: thanks for merging!

**Comment by leaanthony** [comment]
Thanks for being part of the community!

**Pull request closed without merging**
