### PR TITLE
chore: remove the `v1` content from default branch

### PR DESCRIPTION
**Pull request by misitebao**
Resolve: https://github.com/wailsapp/wails/issues/2640

After merging, please set the `v1` branch as a protected branch.

### CODE REVIEW

**Comment by leaanthony** [comment]
What is the impact to projects using v1? For instance Wally is still using it. Extract from `go.mod`:

`github.com/wailsapp/wails v1.16.7`

**Comment by misitebao** [comment]
> What is the impact to projects using v1? For instance Wally is still using it. Extract from `go.mod`:
> 
> `github.com/wailsapp/wails v1.16.7`
> 
> I'm thinking the tags should still be there...?

I don't think this will affect it. When go imports a package, it first looks for it based on the tag, which has nothing to do with the branch.

**Comment by leaanthony** [comment]
If @stffabi is ok with this then I think we're good. I can't think of anything right now that might be an issue.

**Comment by stffabi** [comment]
I'm also fine doing this. Should also make it clear `v1` is EoL. Thanks @misitebao for doing this.

**Comment by misitebao** [comment]
> Should also make it clear `v1` is EoL.

This can be explained in README or documentation, because `go module` does not have a command like `npm deprecate`. 🤣

**Comment by stffabi** [comment]
> > Should also make it clear `v1` is EoL.
> 
> @stffabi @leaanthony This can be explained in README or documentation, because `go module` does not have a command like `npm deprecate`. 🤣

I think I didn't express myself right. I meant it's already very clear `v1` is unmaintained, but with removing the code from master this also makes it somehow final. So everything is fine 😄

**Review by leaanthony — APPROVED** [review]

**Pull request merged**
