### PR TITLE
ensure webkit/gtk callbacks run on main thread

### LINKED ISSUE #1268: [v2] Linux - random SIGABRT on start
**Description**
I've observed wails apps crashing at random intervals on start (observed on Archlinux and Ubuntu 20.04).

**To Reproduce**
Steps to reproduce the behaviour:

Start the same wails app multiple times until it crashes - random :-1: 

**Expected behaviour**
No SIGABRT should occur

**Screenshots**
If applicable, add screenshots to help explain your problem. Here's a sample output from a crash on startup:
```
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
SIGABRT: abort
PC=0x7fe6628c434c m=7 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fe6628c434c
stack: frame={sp:0x7fe634a26f10, fp:0x0} stack=[0x7fe634227950,0x7fe634a27550)
0x00007fe634a26e10:  0x0000000000000000  0x0000000000cf2dd0 
0x00007fe634a26e20:  0x0000000000000028  0x00007fe634a26e70 
0x00007fe634a26e30:  0x0000000000cd02a0  0x00007fe662a99108 
0x00007fe634a26e40:  0x000000000000008d  0x00007fe662a6563c 
0x00007fe634a26e50:  0x000000000000002d  0x0000002000f0c380 
0x00007fe634a26e60:  0x00007fe662a64c50  0x0000000000f0c380 
0x00007fe634a26e70:  0x00007fe600000028  0x0000000000000000 
0x00007fe634a26e80:  0x0000000000000000  0x00007fe66930d1c7 
0x00007fe634a26e90:  0x00007fe6692c7510  0x00007fe66546f290 
0x00007fe634a26ea0:  0x0000000071211810  0x00007fe6654d5aac 
0x00007fe634a26eb0:  0x0000000000000001  0x00007fe66930d6c8 
0x00007fe634a26ec0:  0x00000000000018e2  0x00007fe6654954c8 
0x00007fe634a26ed0:  0x00007fe6692c7510  0x00007fe634a26f68 
0x00007fe634a26ee0:  0x00007fe634a26f64  0x0000000000c69e90 
0x00007fe634a26ef0:  0x0000000000000000  0x0000002800000000 
0x00007fe634a26f00:  0x00007fe6654954c8  0x00007fe6628c433e 
0x00007fe634a26f10: <0x0000000071211810  0x00007fe634a26f64 
0x00007fe634a26f20:  0x0000000001c48460  0x00007fe65e10ba18 
0x00007fe634a26f30:  0x000000000000008e  0x0000000000400f20 
0x00007fe634a26f40:  0x00007fe634a27030  0x00007fe634a27020 
0x00007fe634a26f50:  0x0000000000cd02a0  0x0000000000b82e00 
0x00007fe634a26f60:  0x0000000000c69e90  0x0000000000000000 
0x00007fe634a26f70:  0x0000000000b87e50  0x0000000071211810 
0x00007fe634a26f80:  0x00007fe634a270c0  0x0000000000402d35 
0x00007fe634a26f90:  0x00007fe66933b610  0x5ebd1718228e1600 
0x00007fe634a26fa0:  0x00007fe634a28640  0x0000000000000006 
0x00007fe634a26fb0:  0x0000000000000001  0x00007fe634a27160 
0x00007fe634a26fc0:  0x00007fe634a27280  0x00007fe6628774b8 
0x00007fe634a26fd0:  0x00007fe662a31990  0x00007fe662861534 
0x00007fe634a26fe0:  0x0000000000000020  0x0000000000000000 
0x00007fe634a26ff0:  0x00007fe66933b2a0  0x00007fe66933b610 
0x00007fe634a27000:  0x0000000000000000  0x0000000000b87ea0 
runtime: unknown pc 0x7fe6628c434c
stack: frame={sp:0x7fe634a26f10, fp:0x0} stack=[0x7fe634227950,0x7fe634a27550)
0x00007fe634a26e10:  0x0000000000000000  0x0000000000cf2dd0 
0x00007fe634a26e20:  0x0000000000000028  0x00007fe634a26e70 
0x00007fe634a26e30:  0x0000000000cd02a0  0x00007fe662a99108 
0x00007fe634a26e40:  0x000000000000008d  0x00007fe662a6563c 
0x00007fe634a26e50:  0x000000000000002d  0x0000002000f0c380 
0x00007fe634a26e60:  0x00007fe662a64c50  0x0000000000f0c380 
0x00007fe634a26e70:  0x00007fe600000028  0x0000000000000000 
0x00007fe634a26e80:  0x0000000000000000  0x00007fe66930d1c7 
0x00007fe634a26e90:  0x00007fe6692c7510  0x00007fe66546f290 
0x00007fe634a26ea0:  0x0000000071211810  0x00007fe6654d5aac 
0x00007fe634a26eb0:  0x0000000000000001  0x00007fe66930d6c8 
0x00007fe634a26ec0:  0x00000000000018e2  0x00007fe6654954c8 
0x00007fe634a26ed0:  0x00007fe6692c7510  0x00007fe634a26f68 
0x00007fe634a26ee0:  0x00007fe634a26f64  0x0000000000c69e90 
0x00007fe634a26ef0:  0x0000000000000000  0x0000002800000000 
0x00007fe634a26f00:  0x00007fe6654954c8  0x00007fe6628c433e 
0x00007fe634a26f10: <0x0000000071211810  0x00007fe634a26f64 
0x00007fe634a26f20:  0x0000000001c48460  0x00007fe65e10ba18 
0x00007fe634a26f30:  0x000000000000008e  0x0000000000400f20 
0x00007fe634a26f40:  0x00007fe634a27030  0x00007fe634a27020 
0x00007fe634a26f50:  0x0000000000cd02a0  0x0000000000b82e00 
0x00007fe634a26f60:  0x0000000000c69e90  0x0000000000000000 
0x00007fe634a26f70:  0x0000000000b87e50  0x0000000071211810 
0x00007fe634a26f80:  0x00007fe634a270c0  0x0000000000402d35 
0x00007fe634a26f90:  0x00007fe66933b610  0x5ebd1718228e1600 
0x00007fe634a26fa0:  0x00007fe634a28640  0x0000000000000006 
0x00007fe634a26fb0:  0x0000000000000001  0x00007fe634a27160 
0x00007fe634a26fc0:  0x00007fe634a27280  0x00007fe6628774b8 
0x00007fe634a26fd0:  0x00007fe662a31990  0x00007fe662861534 
0x00007fe634a26fe0:  0x0000000000000020  0x0000000000000000 
0x00007fe634a26ff0:  0x00007fe66933b2a0  0x00007fe66933b610 
0x00007fe634a27000:  0x0000000000000000  0x0000000000b87ea0 

goroutine 1 [syscall]:
runtime.cgocall(0x62ecf0, 0xc0002bde38)
	/usr/lib/go/src/runtime/cgocall.go:156 +0x5c fp=0xc0002bde10 sp=0xc0002bddd8 pc=0x40a11c
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux._Cfunc_loadIndex(0xc69e90)
	_cgo_gotypes.go:1275 +0x45 fp=0xc0002bde38 sp=0xc0002bde10 pc=0x61ce85
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Window).Run.func3(0x61e74f)
	/data/Projects/wails/v2/internal/frontend/desktop/linux/window.go:768 +0x3b fp=0xc0002bde70 sp=0xc0002bde38 pc=0x6242fb
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Window).Run(0xc0002aa230)
	/data/Projects/wails/v2/internal/frontend/desktop/linux/window.go:768 +0x3d fp=0xc0002bde88 sp=0xc0002bde70 pc=0x62419d
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).Run(0xc0002aa1c0, {0x7264e0, 0xc0002865d0})
	/data/Projects/wails/v2/internal/frontend/desktop/linux/frontend.go:130 +0xbd fp=0xc0002bdec8 sp=0xc0002bde88 pc=0x61e75d
github.com/wailsapp/wails/v2/internal/appng.(*App).Run(0xc00029e050)
	/data/Projects/wails/v2/internal/appng/app_production.go:38 +0x31 fp=0xc0002bdf00 sp=0xc0002bdec8 pc=0x62c051
github.com/wailsapp/wails/v2.Run(0xc0000001a0)
	/data/Projects/wails/v2/wails.go:24 +0x33 fp=0xc0002bdf18 sp=0xc0002bdf00 pc=0x62c813
main.main()
	/data/Projects/rdms/main.go:42 +0x45b fp=0xc0002bdf80 sp=0xc0002bdf18 pc=0x62cffb
runtime.main()
	/usr/lib/go/src/runtime/proc.go:255 +0x227 fp=0xc0002bdfe0 sp=0xc0002bdf80 pc=0x43c1a7
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0002bdfe8 sp=0xc0002bdfe0 pc=0x468fa1

goroutine 34 [chan receive]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startMessageProcessor(0x0)
	/data/Projects/wails/v2/internal/frontend/desktop/linux/frontend.go:111 +0x59
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend
	/data/Projects/wails/v2/internal/frontend/desktop/linux/frontend.go:96 +0x387

goroutine 35 [chan receive]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.(*Frontend).startRequestProcessor(0x0)
	/data/Projects/wails/v2/internal/frontend/desktop/linux/frontend.go:287 +0x5a
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend
	/data/Projects/wails/v2/internal/frontend/desktop/linux/frontend.go:97 +0x3c9

rax    0x0
rbx    0x7fe634a28640
rcx    0x7fe6628c434c
rdx    0x6
rdi    0x89526
rsi    0x8952c
rbp    0x8952c
rsp    0x7fe634a26f10
r8     0x7fe634a26fe0
r9     0x8
r10    0x8
r11    0x246
r12    0x6
r13    0x7fe634a27160
r14    0x7fe634a27280
r15    0x0
rip    0x7fe6628c434c
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```
**Additional context**
- the reason is likely a race condition.

### LINKED ISSUE #1288: [v2] Linux - application hangs or SIGABRT when runtime function is called in beforeClose
**Description**
Closing the wails application with ALT-F4 or pressing the window close button results in random hangs/SIGABRT when a call to a runtime function such as `runtime.WindowGetSize()` is called in `App.beforeClose()` 

**To Reproduce**
Steps to reproduce the behaviour:

1. add a call to a runtime function calling the underlying gtk engines in your App.beforeClose method such as:
```go
func (b *App) beforeClose(ctx context.Context) bool {
	w, h := runtime.WindowGetSize(b.ctx)
	log.Println(fmt.Sprintf("in beforeClose: queried runtime.WindowGetSize -> %dx%d", w, h))

	return false
}
```
2. Compile the app and run it several times, closing it after receiving `App.domReady` callback
3. The following kind of errors happen:
```
╰─>$ ./build/bin/rdms
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
2022/03/28 08:32:46 domready from go 2022-03-28 08:32:46.094395794 +0200 CEST
2022/03/28 08:32:47 in beforeClose: queried runtime.WindowGetSize -> 2560x1384
2022/03/28 08:32:47 shutdown
┬─[florent@local:/d/P/rdms]─[08:32:47]
╰─>$ ./build/bin/rdms
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
2022/03/28 08:32:48 domready from go 2022-03-28 08:32:48.886467695 +0200 CEST
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
rdms: xcb_io.c:171: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
┬─[florent@local:/d/P/rdms]─[08:32:50]
╰─>$ ./build/bin/rdms
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
2022/03/28 08:32:59 domready from go 2022-03-28 08:32:59.156421665 +0200 CEST
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
rdms: xcb_io.c:721: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
fish: Job 1, './build/bin/rdms' terminated by signal SIGABRT (Abort)
┬─[florent@local:/d/P/rdms]─[08:33:01]
```

**Expected behaviour**
A function to a runtime call in beforeClose should not produce a SIGABRT.

**System Details**
Using "bleeding-edge master, here's the output of wails doctor:

```
System
------
OS:			Arch Linux
Version: 		Unknown
ID:			arch
Go Version:		go1.17.8
Platform:		linux
Architecture:		amd64
Package Manager: 	pacman

Dependency	Package Name	Status		Version
----------	------------	------		-------
*docker		docker		Installed	20.10.14
gcc		gcc		Installed	11.2.0-4
libgtk-3	gtk3		Installed	1:3.24.33-2
libwebkit	webkit2gtk	Installed	2.36.0-1
npm		npm		Installed	8.5.5
pkg-config	pkgconf		Installed	1.8.0-1

* - Optional Dependency
```

**Additional context**
Debugging the crash in GDB I see on thread 14:

```
Thread 14 (Thread 0x7fab6813dfc0 (LWP 203989)):
#0  0x00007fab6fe617f0 in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#1  0x00007fab6fed28a8 in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#2  0x00007fab6fed4a1d in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#3  0x00007fab6ffacc26 in  () at /usr/lib/libwebkit2gtk-4.0.so.37
#4  0x00007fab6caabb35 in g_object_unref (_object=<optimized out>) at ../glib/gobject/gobject.c:3678
#5  g_object_unref (_object=0x2962c40) at ../glib/gobject/gobject.c:3553
#6  0x00007fab6ec39ba0 in gtk_box_forall (container=<optimized out>, include_internals=<optimized out>, callback=0x7fab6eeb5160 <gtk_widget_destroy>, callback_data=0x0) at ../gtk/gtk/gtkbox.c:2678
#7  0x00007fab6ec886dc in gtk_container_destroy (widget=0x2afe1c0 [GtkBox]) at ../gtk/gtk/gtkcontainer.c:1702
#11 0x00007fab6cabb824 in <emit signal ??? on instance 0x2afe1c0 [GtkBox]> (instance=instance@entry=0x2afe1c0, signal_id=<optimized out>, detail=detail@entry=0) at ../glib/gobject/gsignal.c:3553
    #8  0x00007fab6ca9decd in g_closure_invoke (closure=0x286ebe0, return_value=0x0, n_param_values=1, param_values=0x7ffe42f04e10, invocation_hint=0x7ffe42f04d90) at ../glib/gobject/gclosure.c:830
    #9  0x00007fab6cab9b11 in signal_emit_unlocked_R (node=node@entry=0x2871fe0, detail=detail@entry=0, instance=instance@entry=0x2afe1c0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffe42f04e10) at ../glib/gobject/gsignal.c:3861
    #10 0x00007fab6cabb5c7 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffe42f04fc0) at ../glib/gobject/gsignal.c:3496
--Type <RET> for more, q to quit, c to continue without paging--c
#12 0x00007fab6eec3ede in gtk_widget_dispose (object=0x2afe1c0 [GtkBox]) at ../gtk/gtk/gtkwidget.c:12166
#13 0x00007fab6caabbb2 in g_object_run_dispose (object=0x2afe1c0 [GtkBox]) at ../glib/gobject/gobject.c:1268
#14 0x00007fab6eed4bfa in gtk_window_forall (container=0x29ce2a0 [GtkWindow], include_internals=0, callback=0x7fab6eeb5160 <gtk_widget_destroy>, callback_data=0x0) at ../gtk/gtk/gtkwindow.c:8597
#15 0x00007fab6ec886dc in gtk_container_destroy (widget=0x29ce2a0 [GtkWindow]) at ../gtk/gtk/gtkcontainer.c:1702
#19 0x00007fab6cabb824 in <emit signal ??? on instance 0x29ce2a0 [GtkWindow]> (instance=instance@entry=0x29ce2a0, signal_id=<optimized out>, detail=detail@entry=0) at ../glib/gobject/gsignal.c:3553
    #16 0x00007fab6ca9df8f in g_closure_invoke (closure=0x286ebe0, return_value=0x0, n_param_values=1, param_values=0x7ffe42f052c0, invocation_hint=0x7ffe42f05240) at ../glib/gobject/gclosure.c:830
    #17 0x00007fab6cab9b11 in signal_emit_unlocked_R (node=node@entry=0x2871fe0, detail=detail@entry=0, instance=instance@entry=0x29ce2a0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffe42f052c0) at ../glib/gobject/gsignal.c:3861
    #18 0x00007fab6cabb5c7 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffe42f05470) at ../glib/gobject/gsignal.c:3496
#20 0x00007fab6eec3ede in gtk_widget_dispose (object=0x29ce2a0 [GtkWindow]) at ../gtk/gtk/gtkwidget.c:12166
#21 0x00007fab6eed02e1 in gtk_window_dispose (object=0x29ce2a0 [GtkWindow]) at ../gtk/gtk/gtkwindow.c:3167
#22 0x00007fab6caabbb2 in g_object_run_dispose (object=0x29ce2a0 [GtkWindow]) at ../glib/gobject/gobject.c:1268
#23 0x00007fab6ed67d1b in gtk_main_do_event (event=<optimized out>) at ../gtk/gtk/gtkmain.c:1837
#24 gtk_main_do_event (event=<optimized out>) at ../gtk/gtk/gtkmain.c:1691
#25 0x00007fab6eac8d43 in _gdk_event_emit (event=0x28d0210) at ../gtk/gdk/gdkevents.c:73
#26 _gdk_event_emit (event=0x28d0210) at ../gtk/gdk/gdkevents.c:67
#27 0x00007fab6eb167f8 in gdk_event_source_dispatch.lto_priv () at ../gtk/gdk/x11/gdkeventsource.c:351
#28 0x00007fab735cf163 in g_main_dispatch (context=0x2871850) at ../glib/glib/gmain.c:3417
#29 g_main_context_dispatch (context=0x2871850) at ../glib/glib/gmain.c:4135
#30 0x00007fab736259e9 in g_main_context_iterate.constprop.0 (context=0x2871850, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4211
#31 0x00007fab735ce6a3 in g_main_loop_run (loop=0x295df30) at ../glib/glib/gmain.c:4411
#32 0x00007fab6ed5d94f in gtk_main () at ../gtk/gtk/gtkmain.c:1329
```
while in thread 1:
```
Thread 1 (Thread 0x7fab3bfff640 (LWP 203992)):
#0  0x00007fab6c90f34c in __pthread_kill_implementation () at /usr/lib/libc.so.6
#1  0x00007fab6c8c24b8 in raise () at /usr/lib/libc.so.6
#2  0x00007fab6c8ac5c6 in abort () at /usr/lib/libc.so.6
#3  0x00007fab6c8ac45c in _nl_load_domain.cold () at /usr/lib/libc.so.6
#4  0x00007fab6c8bb116 in  () at /usr/lib/libc.so.6
#5  0x00007fab6b41aae6 in _XReply () at /usr/lib/libX11.so.6
#6  0x00007fab6b3ffde6 in XGetWindowProperty () at /usr/lib/libX11.so.6
#7  0x00007fab6eb2dfaa in _gdk_x11_screen_get_monitor_work_area (area=0x7fab3bffe2f0, monitor=0x2845250 [GdkX11Monitor], screen=0x285e020 [GdkX11Screen]) at ../gtk/gdk/x11/gdkscreen-x11.c:284
#8  _gdk_x11_screen_get_monitor_work_area (area=0x7fab3bffe2f0, monitor=0x2845250 [GdkX11Monitor], screen=0x285e020 [GdkX11Screen]) at ../gtk/gdk/x11/gdkscreen-x11.c:238
#9  gdk_x11_monitor_get_workarea (monitor=0x2845250 [GdkX11Monitor], dest=0x7fab3bffe380) at ../gtk/gdk/x11/gdkmonitor-x11.c:69
#10 0x00007fab6eed5272 in gtk_window_guess_default_size (window=window@entry=0x29ce2a0 [GtkWindow], width=width@entry=0x7fab3bffe420, height=height@entry=0x7fab3bffe41c) at ../gtk/gtk/gtkwindow.c:6535
#11 0x00007fab6eed5fc7 in gtk_window_compute_configure_request_size (height=0x7fab3bffe41c, width=0x7fab3bffe420, flags=78, geometry=0x7fab3bffe440, window=0x29ce2a0 [GtkWindow]) at ../gtk/gtk/gtkwindow.c:9436
#12 gtk_window_compute_configure_request (window=window@entry=0x29ce2a0 [GtkWindow], request=request@entry=0x7fab3bffe4d0, geometry=geometry@entry=0x0, flags=flags@entry=0x0) at ../gtk/gtk/gtkwindow.c:9612
#13 0x00007fab6eed6329 in gtk_window_get_size (window=0x29ce2a0 [GtkWindow], width=0xc00001a3e8, height=0xc00001a3ec) at ../gtk/gtk/gtkwindow.c:5533
```
In thread 1 we see the call to `gtk_window_get_size` at sequence 13 while in thread 14 we see the gtk_dispose being called on GTKWindow starting from sequence 22 and then its parent GTKBox starting from sequence 13. There is clearly a race condition happening with our call to getting window geometry on before close and processing of the close event. From what I can, we should not propagate (allow bubbling up) the close event after it's been handled by the application.

### PR DESCRIPTION
**Pull request by napalu**
prevent close event being propagated when handled in app
closes #1268
closes #1288

### CODE REVIEW

**Comment by napalu** [comment]
> Thanks for opening this. What architectures did you test on? 

I've tested this on AMD64 Linux Ubuntu 20.4 and Archlinux - not tested on ARM64 .

**Comment by leaanthony** [comment]
Thanks @ianmjones for testing 🙏 I can't reproduce either. Not sure what to do 🤷

**Comment by napalu** [comment]
The test app I've been testing this with is dead simple - the SIGABRT on start in #1268 hasn't happened since the use of `lockOSThread` and the SIGABRT/hangs on close in #1288 seem to be fixed with the `return TRUE`. Here's the relevant code from my minimal wails app.go

```Go

// startup is called at application startup
func (b *App) startup(ctx context.Context) {
	// Perform your setup here
	b.ctx = ctx

}

// domReady is called after the front-end dom has been loaded
func (b *App) domReady(ctx context.Context) {
	// Add your action here
	log.Printf("domready from go %v\n", time.Now().Local())

}

// shutdown is called at application termination
func (b *App) shutdown(ctx context.Context) {
	// Perform your teardown here
	log.Println("in shutdown")

}

func (b *App) beforeClose(ctx context.Context) bool {
	w, h := runtime.WindowGetSize(b.ctx)
	log.Println(fmt.Sprintf("in beforeClose: queried runtime.WindowGetSize -> %dx%d", w, h))

	return false

}
```

and the index.html I've been using (deliberately loading some large external javascript 
```html
<!DOCTYPE html>
<html lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="icon" href="<%= BASE_URL %>favicon.ico">
    <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.5.207/build/pdf.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.5.207/web/pdf_viewer.js"></script>
    <title><%= htmlWebpackPlugin.options.title %></title>
  </head>
  <body>
    <noscript>
      <strong>We're sorry but <%= htmlWebpackPlugin.options.title %> doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  </body>
</html>
```

I'm surprised you can't reproduce the problems - maybe try with that minimal setup? The hang/SIGABRT on close was tested as follows: start app from command line and close it with ALT-F4 after the `domready` message is printed - the close problems happen every second , third runs without the fix. The SIGABRT on start is trickier which is why it took me a lot of time to even get a good stacktrace - I could start the app 20-30 times without problems and then pause and get a SIGABRT on the next run.

**Comment by leaanthony** [comment]
I wonder if the gtk/webkit version is affecting this. Genuinely can't reproduce the SIGABRT.

**Comment by napalu** [comment]
> I wonder if the gtk/webkit version is affecting this. Genuinely can't reproduce the SIGABRT.

image

bleeding-edge without the close and osLockThread fix - random SIGABRT on close - here right on 1st run

image

coredump debug:

image

Out of interest if you run you app from a terminal - what terminal are you using What's your GTK and webkit2gtk versions? I'm seeing the problem running from kitty and terminator (the 2 terminals I use most often). Testing in XTerm - hang on close after second run.

image

Then hang on close on 3rd run and SIGABRT on 6th close:

image

**Comment by napalu** [comment]
On Ubuntu 20.04

image

after 9 runs with ALT-F4 to close:

image

If it was only one system I'd say it's not reproduceable but that's not the case

**Comment by leaanthony** [comment]
Let's keep the 2 issues seperate. The close issue is an issue. The thing that's hard to reproduce is the SIGABRT without the LockOSThread. Can we split the PR into 2 so we can fix close and look at this separately? Thanks 🙏

**Comment by napalu** [comment]
Okay closing this and splitting the 2 PRs. I started bisecting to pinpoint #1268 and was able to reproduce it in 3d12935e2e501d8599c82b7c5638c8593f337c22 but since it's so random and hard to reproduce I gave up. For what's it worth, I have been not been able to reproduce #1268 in latest master (with or without the lockOSThread fix). I don't think the lockOSThread fix breaks anything but might as well close the associated PR and issue  - can always reopen it if #1268 resurfaces.

**Comment by napalu** [comment]
reopened to test #1316

**Pull request closed without merging**
