### PR TITLE
[v3, darwin] Fix leaking WebKit processes on Window close

### LINKED ISSUE #2565: v3:  open Multiple Windows and then close, then webkit background process not closed
### Description

use then project examples of window, when the child window opend and then close it, the webkit background process not closed

### To Reproduce

run the example of : go run wails/v3/examples/window/main.go

### Expected behaviour

the background proess while exit when the sub windows exit

### Screenshots

open 10 sub windows

the background process is:

when i closed the sub windows, the background process still exist, not exit with the window.

### Attempted Fixes

_No response_

### System Details

```shell
Wails CLI v2.3.1

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | MacOS   
Version      | 13.2.1  
ID           | 22D68   
Go Version   | go1.19.2
Platform     | darwin  
Architecture | amd64   

# Wails

Version | v2.3.1

# Dependencies

Dependency                | Package Name | Status    | Version      
Xcode command line tools  | N/A          | Installed | 2396         
npm                       | N/A          | Installed | 9.4.1        
*Xcode                    | N/A          | Installed | 14.1 (14B47b)
*upx                      | N/A          | Installed | upx 3.96     
*nsis                     | N/A          | Installed | v3.08        
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by stffabi**
Fixes #2565

### CODE REVIEW

**Comment by leaanthony** [comment]
This works a treat! I've added some code to remove the window from the application map which may fix the rest of the leak. Also added HideOnClose as it would affect the logic of this. LMK if this sorts out the rest of the leak

**Comment by tmclane** [comment]
FYI: I rebased on `master` and `force-pushed` to remove the `merge from main to the branch` commit.    Should make for a clean merge if the button were pushed now.  (I can't do it.)

**Comment by stffabi** [comment]
@tmclane we almost always do a "squash and merge" or "rebase and merge" for PRs, so the `merge from main to the branch` commit never lands on master.

@leaanthony LGTM, I think we can merge this one.

**Comment by tmclane** [comment]
Ok.  Glad to hear it.  There shouldn't be any need to merge from `master` to the branch which I've  seen some times in the repo if that is done.  Makes the history much cleaner and easier to see where it is located.   I'll refrain from helping in that way then.

**Comment by stffabi** [comment]
Merging from `master` to branch makes sense for keeping the branch up to date, especially if work is still ongoing on both sides and multiple people are involved. We might make contributors very unhappy if we force-push their branches where they are probably still working on.
So I would say if those commits landed on master that were mainly mistakes.

I fully agree with you that when merging the branch/PR we should make sure to have a clean history and make sure we do a `rebase and merge` or `squash and merge`. But this should only be done when we finally merge the PR/branch and should not be done when work is still ongoing from other people.

**Comment by tmclane** [comment]
bear in mind they have their own copy of the branch locally as well. We aren't actually force-pushing their branch while it's in development.  My intent was that the maintainer (which might be the github interface) do the rebase - resolve the conflicts, then merge it to `main/master` such that the history is clean.  If it's a squash commit instead that accomplishes the same thing ultimately.  I don't personally like to squash everything since I usually do that before I open the MR and my commits are to the best of my ability "meaningful" already.  I really dislike the 'fixup' or 'oops' types of commits in the history.  Those should be squashed locally before pushing.  

If the 'developer' rebases their local branch on 'master' periodically then they accomplish the same thing as a merge from the same branch.   The history becomes part of their branch either way but the rebase is nicer IMO.   
It sounds like things are happening the way I was hoping for basically anyhow so I am going to let this go.

**Comment by stffabi** [comment]
Yeah they have their local copy, but when you force-push the remote branch on github you basically force the developer to do react in some way to be able to push again. Or even multiple developers, e.g. in this case there were multiple developers involved.

We have some different expectations on how PRs and branches should be kept up-to-date and when to force-push or not, but that's just fine and people don't always have to find a consent.

**Comment by tmclane** [comment]
Fair enough.  I'll refrain from doing it in the future.  I only did it today so that it would `merge cleanly` instead of needing another rebase by the UI.

**Comment by leaanthony** [comment]
For what it's worth, I'm less worried about git history than most :-) I know that makes me a bad person 😂

**Pull request merged**
