### PR TITLE
Implement custom protocol association support

### PR DESCRIPTION
**Pull request by APshenkin**
# Description

Implements custom protocol association support for macOS/Windows. This will allow connect web apps with desktop apps builded with Wails

Users can specify list of custom protocols in `wails.json` config with following params
```
"scheme": :"Custom Protocol scheme. e.g. myapp"
"description": "Windows-only. The description."
"role": "macOS-only. The app’s role with respect to the type. Corresponds to CFBundleTypeRole."
```

Few comments regarding implementation
MacOS: Darwin handle opening file by raising `handleGetURLEvent` event. Callback is added for app configuration to handle this correctly.
Windows: On Windows protocols association is done via NSIS installer. So apps should be distributed with it to have this feature. 
When custom protocol URL is opened, Windows launches new instance of the app and pass url as argument. So apps developers should parse args and handle situation properly.
Linux: To setup association changes on client system should be done. As wails doesn't support bundling for linux now, nothing was added in this PR for it, but in test repo that is provided below you can see how this can be done using nfmp. Also this is added in guides.

You can see how it works here.
- [x] [Windows](https://github.com/wailsapp/wails/assets/14344430/5f43c370-c782-4711-a50d-d19c2db563fd)
- [x] [MacOs](https://github.com/wailsapp/wails/assets/14344430/a0b745e7-95cc-401b-b9bf-79b35b3cb271)
- [x] [Linux](https://github.com/wailsapp/wails/assets/14344430/8cabebab-f8d4-4330-beae-c7a45d7f1854) – NOTE THIS IS NOT PART OF PR AS WAILS DOESN'T SUPPORT BUNDLING FOR LINUX. But it can be done manually using bundling (docs added for this)

Fixes # (issue)

## Type of change
  
Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
  
Test repo is available here https://github.com/APshenkin/wails-open-file/tree/feature/deeplinks
PR should be fetched and replace in go.mod should be adjusted

- [x] Windows
- [x] macOS
- [x] Linux
  
## Test Configuration

```
# Wails
Version  | v2.6.0
Revision | a419721dcdf16da7a4afd92b9ba63b2050229a26
Modified | true

# System
┌─────────────────────────┐
| OS           | MacOS    |
| Version      | 13.5.2   |
| ID           | 22G91    |
| Go Version   | go1.20.2 |
| Platform     | darwin   |
| Architecture | arm64    |
└─────────────────────────┘


# System
┌────────────────────────────────────┐
| OS           | Windows 10 Pro      |
| Version      | 2009 (Build: 22621) |
| ID           | 22H2                |
| Go Version   | go1.21.1            |
| Platform     | windows             |
| Architecture | arm64               |
└────────────────────────────────────┘                         

# System
┌────────────────────────────────────┐
| OS           | Ubuntu              |
| Version      | 22.04               |
| ID           | ubuntu              |
| Go Version   | go1.21.1            |
| Platform     | linux               |
| Architecture | arm64               |
└────────────────────────────────────┘

```

# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by APshenkin** [comment]
@leaanthony @stffabi please take a look on this too 😊

This feature will be really handy in case when devs have web app and want to open desktop app builded with wails in some cases

**Comment by APshenkin** [comment]
@leaanthony sorry for ping you, just want to check if you saw this PR :)

**Comment by leaanthony** [comment]
Sorry, I've not been feeling too good so haven't been in the right headspace for this. Others can take a look in the meantime

**Comment by APshenkin** [comment]
@leaanthony @stffabi 
Just kind reminder about this 🙂

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
I'm good with this PR. Thanks so much for spending the time doing it and your patience. I'll just give @stffabi a couple of days to look at it and we'll get it in. Thanks again 🙏

**Comment by annismckenzie** [comment]
Would this be available in a 2.x release when it's merged? 😅

**Review by stffabi — APPROVED** [review]
LGTM 🚀 

Thanks so much for this awesome PR @APshenkin and taking the time to do this 🙏 .

**Comment by stffabi** [comment]
> Would this be available in a 2.x release when it's merged? 😅

Yes, this PR is targeting v2.

**Comment by leaanthony** [comment]
Thanks again @APshenkin! You're filling my v3 backlog by stealth 😅

**Comment by APshenkin** [comment]
@leaanthony I'm really excited about Wails (and it's V3 as well) and planing to do some app with it 🙂
Just cause v3 is still in active development – wanted to speed up things that are critical for me.

Maybe will introduce some more PRs if will face some features in Wails more 😊

**Comment by byteams** [comment]
Hi folks, I'm unable to get this to work on a mac. Tried open("customapp://localhost:port/path") like in the vid but it complains that there is no registered scheme handler for customapp://. Is there any plan to update the documentations on how to achieve this?

**Comment by byteams** [comment]
Hi folks, I'm unable to get this to work on a mac. Tried open("customapp://localhost:port/path") like in the vid but it complains that there is no registered scheme handler for customapp://. Is there any plan to update the documentations on how to achieve this?

**Comment by leaanthony** [comment]
@byteams - thanks for reporting this. Perhaps it's best to open a new issue rather than an old PR. Might also be worth mentioning @APshenkin to see if he's still around.

**Comment by byteams** [comment]
@leaanthony gotcha ok. Let me create a new issue this weekend. Thanks btw for this awesome project.

**Pull request merged**
