### PR TITLE
chore: removed incorrect go.mod instructions

### LINKED ISSUE #3877: Unnecessary instruction for updating go.mod file for new projects.
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

The documentation mentions the following when creating a new project

`The default module name in go.mod is "changeme". You should change this to something more appropriate.`

I have just created a new project myself and gone to the go.mod file to find that it no longer uses 'changeme' as the default project name.

### Self-service

- [X] I'd be willing to address this documentation request myself.

### PR DESCRIPTION
**Pull request by damiensedgwick**
# Description

This change removes references of `The default module name in go.mod is "changeme". You should change this to something more appropriate.` which are no longer necessary as creating a new wails project uses the project name correctly.

Fixes #3877

## Type of change
  
Please delete options that are not relevant.

- [X] This change requires a documentation update

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [X] Windows
- [ ] macOS
- [X] Linux
  
 I have checked both windows and linux as I am using WSL.
  
## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

Using WSL I built and served the documentation website and confirmed that the unnecessary message is no longer being displayed.

# Checklist:

- [X] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [X] My code follows the general coding style of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Introduced a tabbed interface for project generation using the `wails init` command, supporting frameworks like Svelte, React, Vue, Preact, Lit, and Vanilla.
	- Enhanced documentation clarity regarding the project layout and directory structure.
	- Added community templates and references to CLI help for additional options.

- **Bug Fixes**
	- Removed outdated note about changing the default module name in `go.mod`, simplifying instructions.

- **Documentation**
	- Updated various sections to improve usability and clarity for new users setting up Wails projects.

### CODE REVIEW

**Comment by leaanthony** [comment]
Nice find!🙏 Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

**Comment by damiensedgwick** [comment]
> Nice find!🙏 Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

Thank you. I did add to the changelog yesterday after I spotted the checkbox in the PR description., if you could let me know if anything needs changing and then I can address it later.

image

**Comment by leaanthony** [comment]
I must have responded to an older version of this page :-)

**Comment by damiensedgwick** [comment]
Do I have to do anything else here @leaanthony or will it just get picked up when it gets picked up? I merged master back in so it didn't fall too far behind.

**Comment by damiensedgwick** [comment]
Do I have to do anything else here @leaanthony or will it just get picked up when it gets picked up? I merged master back in so it didn't fall too far behind.

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Thanks for this! 🙏

**Pull request merged**
