### PR TITLE
react template

### PR DESCRIPTION
**Pull request by bh90210**

### CODE REVIEW

**Comment by leaanthony** [comment]
Changed PR to be against develop branch and there's a conflict with CONTRIBUTORS.md. I've updatd this locally and pushed using the commans github gives you but this PR is still showing as open. Can you please resolve the conflict on your side and see if it nudges the PR? Thanks :-)

**Comment by bh90210** [comment]
done.
should I push any future PR in develop branch or should I make a new branch? have you written some guideline about that?

**Comment by leaanthony** [comment]
Thanks! Always against develop. I wrote up about it [here](https://wails.app/development/) but let me know if that doesn't make sense or I need to also add this information elsewhere. I should probably add it to the issue tracker...

**Comment by bh90210** [comment]
nope, documentation is fine. I just got lazy I guess, and never went through it before the PR.

**Pull request merged**
