### PR TITLE
Possible fix for #2332. Handle anonymous fields with JSON tags as known.

### PR DESCRIPTION
**Pull request by sebastian0x62**

### CODE REVIEW

**Comment by leaanthony** [comment]
Hey there 👋 can you please provide more context for this PR like what it changes and why? Future us will appreciate it 😅

**Comment by sebastian0x62** [comment]
Tried to offer the intended behavior from the referenced issue. When bindings include a struct with an embedded anonymous other struct, generated .ts file and runtime TS type are not the same. Flat vs hierarchy.

This PR handles those fields as not anonym, when a struct tag for JSON marshalling is provided. This way the generated .ts file matches the runtime type.

**Comment by sebastian0x62** [comment]
@leaanthony , I've read, for v3 the whole binding generation stuff is changed. In this case we also can delete this PR since a manual solution with changing such structs manually is still possible.

**Comment by leaanthony** [comment]
@sebastian0x62 - closing as you suggested. Anon structs supported in v3 🎉

**Pull request closed without merging**
