### PR TITLE
[v3] Binding generator using `go/types`

### PR DESCRIPTION
**Pull request by abichinger**
# Description

This PR continues the work done by @fbbdev in https://github.com/wailsapp/wails/pull/3347. I used this commit 241c578c7abe6e8cd916e561f626bb53ce275340 as a starting point and modified the binding and model generator code to work with the `go/types` package. Using `go/types` instead of `go/ast` fixes the problems with object resolution.
https://github.com/wailsapp/wails/pull/3347#issuecomment-2026294489
https://github.com/golang/go/issues/48141#issuecomment-912126040

### Breaking changes

- The identifier of a bound method is now `packagePath.structName.methodName` instead of `packageName.structName.methodName` to avoid collisions (a70289787eeb7dc7b146e885b19340ebf01a88f2)
- `GenerateBindingsOptions.UseIDs` got replaced by `GenerateBindingsOptions.UseNames` making `CallByID` the new default (aa098b73a69bbcc01d7f341b20fc5d6fcc764466)
- I changed the interface of the `parser` package

### New features

- It is possible to bind structs from external packages. An example can be found at [`wails/v3/internal/parser/testdata/multiple_packages`](https://github.com/abichinger/wails/tree/feat/bindgen_v2/v3/internal/parser/testdata/multiple_packages). You can run this example with `go run .`
- go types that are not structs or "enums" generate a Typescript alias type: https://github.com/abichinger/wails/blob/1660a12ba2d0f20e2ab5698b4156432c999b043f/v3/internal/parser/testdata/complex_json/frontend/bindings/main/models.ts#L5
- Support types implementing the [`encoding.TextMarshaler`](https://pkg.go.dev/encoding#TextMarshaler) interface. The resulting Typescript type is `string`. https://github.com/abichinger/wails/blob/1660a12ba2d0f20e2ab5698b4156432c999b043f/v3/internal/parser/testdata/multiple_packages/frontend/bindings/github.com-google-uuid/models.ts#L9

### Fixes

- Use the first constant value of an Enum as default
- The JSDoc [enum](https://jsdoc.app/tags-enum) definition was missing the `<type>` parameter
- The ID of bound methods from a nested package was previously incorrect

### Limitations

- [iota](https://go.dev/wiki/Iota) is not supported to define enums
- It is not possible to bind methods, which accept an interface as parameter
- Interface fields inside structs are dropped
- Generic types are ignored
- Can not bind packages
- Unable to predict fields of types, which implement [`json.Marshaler`](https://pkg.go.dev/encoding/json#Marshaler)

### Downsides

- The new binding generator is significantly slower. In my test project, generation takes 243ms (18 times slower than https://github.com/wailsapp/wails/pull/3347)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

All tests have passed. Some expected results of tests inside `v3/internal/parser/testdata` have been corrected.
The binding example has been tested and updated.
The bindings of a test project have been generated.

- [ ] Windows
- [ ] macOS
- [x] Linux
  
## Test Configuration

```bash
# System
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| Name         | Manjaro Linux                                                                                                  |
| Version      | Unknown                                                                                                        |
| ID           | manjaro                                                                                                        |
| Branding     |                                                                                                                |
| Platform     | linux                                                                                                          |
| Architecture | amd64                                                                                                          |
| CPU          | AMD Ryzen 5 3600 6-Core Processor                                                                              |
| GPU 1        | Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] (Advanced Micro Devices, Inc. [AMD/ATI]) - Driver: amdgpu  |
| Memory       | 32GB                                                                                                           |
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Build Environment
┌─────────────────────────────────────────────────────────────────────────────────────────────────┐
| Wails CLI      | v3.0.0-alpha.4                                                                 |
| Go Version     | go1.22.0                                                                       |
| Revision       | 43418e96f36455467657822f8487d8a567dfda17                                       |
| Modified       | true                                                                           |
| -buildmode     | exe                                                                            |
| -compiler      | gc                                                                             |
| CGO_CFLAGS     |                                                                                |
| CGO_CPPFLAGS   |                                                                                |
| CGO_CXXFLAGS   |                                                                                |
| CGO_ENABLED    | 1                                                                              |
| CGO_LDFLAGS    |                                                                                |
| DefaultGODEBUG | httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1 |
| GOAMD64        | v1                                                                             |
| GOARCH         | amd64                                                                          |
| GOOS           | linux                                                                          |
| vcs            | git                                                                            |
| vcs.modified   | true                                                                           |
| vcs.revision   | 43418e96f36455467657822f8487d8a567dfda17                                       |
| vcs.time       | 2024-04-15T14:26:43Z                                                           |
└─────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────┐
| pkg-config | 2.1.0-2      |
| gcc        | 13.2.1-5     |
| libgtk-3   | 1:3.24.41-1  |
| libwebkit  | 2.42.5-2     |
| npm        | 10.5.0       |
└─ * - Optional Dependency ─┘

# Diagnosis
 SUCCESS  Your system is ready for Wails development!
```

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by fbbdev** [comment]
Hello!

Thank you for this and sorry to everyone for disappearing. As I told @leaanthony, I was swamped in other work for some time.

@leaanthony suggested that we coordinate to compare and integrate our work.

The situation might not be that easy on my part, as I have quite a lot of unpublished work that diverged from what you have now.
I essentially rewrote my own static analyser from scratch, altering its API significantly and fixing some mistakes in the process.
I also had in mind a slightly different (and parallelised) architecture for the generator, and I already laid the groundwork for the part that collects information and renders types. I hope parallelisation could take some time off the generation step on multi-core machines.

I had a cursory look at your implementation. I like how you dealt with documentation, it didn't occur to me to use the doc package. I would definitely integrate that. I didn't have the time to look at the parser and tests yet.

If you and @leaanthony both agree, I suggest that we proceed as follows.
I would like to still bring my current work to completion and publish that to my fork.
Then we might get in contact and compare our code w.r.t. functionality and architecture, and proceed to integrate everything with @leaanthony 's feedback.

What do you think?

**Comment by abichinger** [comment]
Hi!

Sounds good to me! I'm excited to see how much you can improve the performance by using parallelisation.

> I like how you dealt with documentation, it didn't occur to me to use the doc package.

Thanks! Unfortunately, some comments still have to be read from the syntax tree.

**Comment by abichinger** [comment]
I managed to improve the performance a bit. The previously mentioned test project now takes about **175ms** (before: **243ms**) to process. The main performance gain comes from calling `LoadPackages()` only once instead of multiple times. 

During benchmarking, I noticed that `LoadPackages` is by far the most time consuming step. I glanced over the source code of `packages` [[packages.go;l=849](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.20.0:go/packages/packages.go;l=849)] and I think it already runs concurrently. Unfortunately, improving the `packages.Load` function is definitely beyond my skill set. So I guess I can not improve this PR much further.
```shell
Running tool: /usr/bin/go test -benchmem -run=^$ -bench ^BenchmarkParser$ github.com/wailsapp/wails/v3/internal/parser

goos: linux
goarch: amd64
pkg: github.com/wailsapp/wails/v3/internal/parser
cpu: AMD Ryzen 5 3600 6-Core Processor              
BenchmarkParser/struct_literal_single/LoadPackages-12         	       6	 178059021 ns/op	42910514 B/op	  384078 allocs/op
BenchmarkParser/struct_literal_single/ParsePackages-12        	    7263	    167544 ns/op	   67175 B/op	    1407 allocs/op
BenchmarkParser/struct_literal_single/GenerateBindings-12     	    1224	   1021023 ns/op	  190957 B/op	    5965 allocs/op
BenchmarkParser/struct_literal_single/GenerateModels-12       	    8622	    141129 ns/op	   32852 B/op	     792 allocs/op
BenchmarkParser/complex_json/LoadPackages-12                  	       6	 186976808 ns/op	42683781 B/op	  381728 allocs/op
BenchmarkParser/complex_json/ParsePackages-12                 	   15997	     89820 ns/op	   27963 B/op	     647 allocs/op
BenchmarkParser/complex_json/GenerateBindings-12              	   25927	     46426 ns/op	    8937 B/op	     241 allocs/op
BenchmarkParser/complex_json/GenerateModels-12                	    2890	    439030 ns/op	   85824 B/op	    2502 allocs/op
BenchmarkParser/multiple_packages/LoadPackages-12             	       6	 176921930 ns/op	43419330 B/op	  383045 allocs/op
BenchmarkParser/multiple_packages/ParsePackages-12            	      69	  17606685 ns/op	  811619 B/op	   18342 allocs/op
BenchmarkParser/multiple_packages/GenerateBindings-12         	    3015	    437696 ns/op	   86901 B/op	    2411 allocs/op
BenchmarkParser/multiple_packages/GenerateModels-12           	    3022	    373890 ns/op	   80071 B/op	    1954 allocs/op
PASS
ok  	github.com/wailsapp/wails/v3/internal/parser	21.475s
```
`BenchmarkParser/multiple_packages/ParsePackages` takes **17ms**, because `ParsePackages` loads the documentation for each struct coming from an imported package.

**Comment by overlordtm** [comment]
Hey, just want to give some feedback, I have quite complicated models and this is first version of parser that managed to parse it and generate TS models correctly. Only `error` types are still problem, it seems go/types does not handle this.

I have also fixed parse so call to `application.New` can be anywhere, not only in main. Seems it works :D

**Comment by abichinger** [comment]
> Only error types are still problem, it seems go/types does not handle this.

@overlordtm could you provide an example?

**Comment by leaanthony** [comment]
@abichinger - do you have a feature list for this enhancement? I'm thinking this will help with the integration of @fbbdev 's work.

**Comment by abichinger** [comment]
Apart from the bugfixes and features I already mentioned above, this PR is functionally identical to https://github.com/wailsapp/wails/pull/3347.

I think it is best to wait for @fbbdev to publish his new architecture and then we can compare.

**Comment by leaanthony** [comment]
I spoke to @fbbdev earlier and he suggested closing the other PR and concentrating efforts on this, so that's what I'll do.

**Comment by abichinger** [comment]
I would appreciate some feedback on the generated package directories.

The current behaviour is as follows.
1. Services and models inside the project directory will be placed inside `main`.
2. Each subpackage in the project directory ends up in the same subfolder as in the project.
3. External packages get placed inside a folder identical to their package path (`/` is replaced with `-`)

Lets asume our project directory has the package path `github.com/alice/foo`.
Services and models defined inside ...
- `github.com/alice/foo` will end up in `main`
- `github.com/alice/foo/bar` will end up in `bar`
- `github.com/alice/foo/bar/baz` will end up in `bar/baz`
- `log` (standard package) will end up in `log`
- `github.com/google/uuid` will end up in `github.com-google-uuid`

The current solution could still cause collisions. For example, a package `log` inside the project could collide with the standard `log` package.

Do you consider the current solution to be okay?

**Comment by leaanthony** [comment]
Awesome work 😎

I've created a post on discord to discuss the ains/strategy of the parser which I think would be a better forum than GH.

**Comment by leaanthony** [comment]
@abichinger - Can we close this in favour of https://github.com/wailsapp/wails/pull/3468 now? 
@overlordtm - It would be amazing if you could let us know if the next iteration of the parser (linked above ☝️ ) works for your scenarios 🙏

**Comment by abichinger** [comment]
Closing in favour of #3468

**Pull request closed without merging**
