### PR TITLE
configure vite import alias @ by default

### PR DESCRIPTION
**Pull request by tonytony2020**
see also https://github.com/wailsapp/wails/discussions/2074

### CODE REVIEW

**Comment by tonytony2020** [comment]
@leaanthony which branch should I push, feature or chore?

**Comment by misitebao** [comment]
@tonytony2020 
You should use the `feature/*` branch.

**Comment by tonytony2020** [comment]
> @tonytony2020 You should use the `feature/*` branch.

which `feature/*` branch？

**Comment by leaanthony** [comment]
Thanks for opening this @tonytony2020 - Can you please open a ticket explaining the current issue and why this is a good idea. It's difficult to accept a PR without context. Thanks 👍

**Comment by leaanthony** [comment]
Hey @tonytony2020 I'm keen to merge this. Were you pushing updates?

**Comment by OlegGulevskyy** [comment]
Does this update also plays nicely with typescript?
I know I had some troubles with `tsconfig.json` when I am changing path aliases, meaning that `tsconfig.json` will complain about unknown packages that you will try to import from. To fix that, `tsconfig.json` also has to have these path aliases defined.

**Pull request closed without merging**
