### PR TITLE
[dev] Fix panic in devserver when using the logger

### LINKED ISSUE #2480: After upgrading to Wails v2.4.0, panic in default_logger.go
### Description

Apologies if this is a duplicate, but searching for "panic default_logger.go" didn't yield any results)...

After upgrading to v2.4.0, I'm seeing this panic:

```
echo: http: panic serving 127.0.0.1:39792: runtime error: invalid memory address or nil pointer dereference
goroutine 4297 [running]:
net/http.(*conn).serve.func1()
        /usr/local/go/src/net/http/server.go:1854 +0x148
panic({0x2643220, 0x5392d60})
        /usr/local/go/src/runtime/panic.go:890 +0x262
github.com/wailsapp/wails/v2/internal/logger.(*Logger).Error(0x0, {0xc000d44000, 0x2c}, {0xc0008b8160, 0x2, 0x2})
        /home/matt/go/pkg/mod/github.com/wailsapp/wails/v2@v2.4.0/internal/logger/default_logger.go:99 +0x3b
github.com/wailsapp/wails/v2/pkg/assetserver.(*AssetServer).logError(0xc000886b00, {0xc000e170a8, 0x1e}, {0xc0008b8160, 0x2, 0x2})
        /home/matt/go/pkg/mod/github.com/wailsapp/wails/v2@v2.4.0/pkg/assetserver/assetserver.go:206 +0xa5
github.com/wailsapp/wails/v2/pkg/assetserver.(*AssetServer).serveError(0xc000886b00, {0x47ca840, 0xc00128f0e0}, {0x47bf7c0, 0xc0005962d0}, {0x2907315, 0x1a}, {0xc0008b8160, 0x2, 0x2})
        /home/matt/go/pkg/mod/github.com/wailsapp/wails/v2@v2.4.0/pkg/assetserver/assetserver.go:194 +0x190
github.com/wailsapp/wails/v2/pkg/assetserver.(*AssetServer).writeBlob(0xc000886b00, {0x47ca840, 0xc00128f0e0}, {0xc0009580e4, 0x11}, {0xc000c64000, 0x113d5, 0x12000})
        /home/matt/go/pkg/mod/github.com/wailsapp/wails/v2@v2.4.0/pkg/assetserver/assetserver.go:188 +0x16f
github.com/wailsapp/wails/v2/pkg/assetserver.(*AssetServer).ServeHTTP(0xc000886b00, {0x47ca840, 0xc00128f0e0}, 0xc000adc400)
        /home/matt/go/pkg/mod/github.com/wailsapp/wails/v2@v2.4.0/pkg/assetserver/assetserver.go:135 +0x70d
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run.func3({0x47f8e30, 0xc000650a00})
        /home/matt/go/pkg/mod/github.com/wailsapp/wails/v2@v2.4.0/internal/frontend/devserver/devserver.go:118 +0x86
github.com/labstack/echo/v4.(*Echo).add.func1({0x47f8e30, 0xc000650a00})
        /home/matt/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x88
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0008e6240, {0x47cc220, 0xc000a121c0}, 0xc000adc400)
        /home/matt/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x293
net/http.serverHandler.ServeHTTP({0xc0008be2d0}, {0x47cc220, 0xc000a121c0}, 0xc000adc400)
        /usr/local/go/src/net/http/server.go:2936 +0x494
net/http.(*conn).serve(0xc000b4a090, {0x47cd5b8, 0xc000596190})
        /usr/local/go/src/net/http/server.go:1995 +0x19b5
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:3089 +0xa16
```

### To Reproduce

I haven't worked on a minimal reproducer yet, as I'm hoping the stack trace should be enough to find that a logger isn't set somewhere... if you really need a repro let me know and I can try, but I just know that after upgrading from v2.3 to v2.4 this started happening when serving static assets.

### Expected behaviour

No panic

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
$ wails doctor
Wails CLI v2.4.0

Scanning system - Please wait (this may take a long time)...Done.

# System

OS           | Pop!_OS
Version      | 22.04  
ID           | pop    
Go Version   | go1.20 
Platform     | linux  
Architecture | amd64  

# Wails

Version         | v2.4.0
Package Manager | apt   

# Dependencies

Dependency | Package Name          | Status    | Version                  
*docker    | docker.io             | Available | 20.10.21-0ubuntu1~22.04.2
gcc        | build-essential       | Installed | 11.3.0                   
libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2         
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.5-0ubuntu0.22.04.1  
npm        | npm                   | Installed | 8.5.1~ds-1               
*nsis      | nsis                  | Available | 3.08-2                   
pkg-config | pkg-config            | Installed | 0.29.2                   
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details: 
  - docker: sudo apt install docker.io
  - nsis: sudo apt install nsis

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

Thank you for Wails, it keeps getting better :+1:

### PR DESCRIPTION
**Pull request by stffabi**
Fixes #2480

### CODE REVIEW

**Comment by leaanthony** [comment]
I think this is a good candidate for a 4.0.1 release. Happy to do that once @mholt confirms.

**Comment by mholt** [comment]
I've been having trouble reproducing the bug in the first place, so... I can keep trying to produce some sort of error to be logged, but I'd personally trust @stffabi here :sweat_smile:

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Thanks for doing this @stffabi ! I think we can hold off a release unless someone else raises it.

**Comment by stffabi** [comment]
Yeah we can do that 👍

**Pull request merged**
