### PR TITLE
Allow main to start even if no $DISPLAY is set

### PR DESCRIPTION
**Pull request by steely-glint**
I'm not happy with this - ideally the failure would be fed back up to the app, but there didn't seem to be an obvious path to doing that. 
At least with this I can check $DISPLAY in main() and take evasive action....

### CODE REVIEW

**Review by tmclane — COMMENTED** [review]
I'll take a look at this a bit more soon.

**Comment by leaanthony** [comment]
@tmclane - any thoughts on this?

**Comment by leaanthony** [comment]
I think https://github.com/wailsapp/wails/pull/2841 fixed the issue?

**Comment by leaanthony** [comment]
@tmclane - do you think this can be closed now?

**Comment by leaanthony** [comment]
Fixed by https://github.com/wailsapp/wails/pull/2841

**Pull request closed without merging**
