### PR TITLE
Add Korean to doc

### PR DESCRIPTION
**Pull request by jaesung9507**

### CODE REVIEW

**Comment by misitebao** [comment]
You only need to submit the modified "docusaurus.config.js" file, other content will be translated in ["crowdin"](https://crowdin.com/project/wails).

**Comment by jaesung9507** [comment]
@misitebao 
 Can I merge my branch by remove other files and modify "ko" after "ru" in docusaurus.config.js file?

**Comment by leaanthony** [comment]
🙏

**Comment by jaesung9507** [comment]
@leaanthony @misitebao 
I made a join request in crowdin.

**Pull request merged**
