### PR TITLE
implement gopath handling during cross compilation

### PR DESCRIPTION
**Pull request by tmclane**
Allows the developer to specify a `-gopath` path argument during build which is mounted to the docker container at `/go` which is configured as the GOPATH inside the runtime.

Allows the developer to specify a `-gopath` path argument during build which causes the location on your host to be mounted at `/go` inside the cross-compiler container.  
Enabling the `replace github.com/original/library => github.com/tmclane/library` style of substitution where you edit files on the host and they are made available in the cross-compile environment.

Addresses: #460

### CODE REVIEW

**Comment by tmclane** [comment]
Just realized I likely need to make this a sub-command of the `-x` cross-compile sub-command of the `build` command.

**Review by leaanthony — COMMENTED** [review]
Beast mode!

A couple of Qs:

- Did you pull out xgoVersion for $FUTURE_REASONS?
- Is `/go` known to the container? As in, does it hold some significance currently or do we need to update the container too?

**Comment by tmclane** [comment]
/go is the default go path inside the container if not overridden.

**Comment by tmclane** [comment]
I am planning on using xGoVersion to hold the version of the wailsapp/xgo image tag.  Currently it only has latest so of limited value. I want to switch to versioned images so we know what capabilities are available in each one .

**Comment by leaanthony** [comment]
This is sweet.

**Pull request merged**
