### PR TITLE
Change style of doctor command

### PR DESCRIPTION
**Pull request by MarvinJWendt**
Hi, I restyled the `doctor` command a little to make it more appealing. I kept all original details, just added some eye-candy.

### Before
image

### After
image

Let me know what you think 😄 

---

I didn't make a ticket for this, as it's just a little refactor.

### CODE REVIEW

**Comment by leaanthony** [comment]
Well this is a lot of fun! Thanks 🙏 Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

**Comment by MarvinJWendt** [comment]
Done :)

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Thanks for this @MarvinJWendt 🙏

**Comment by misitebao** [comment]
@leaanthony 
This PR has been merged for too long, and two versions were released during this period, resulting in the wrong position of `changelog`. Is it necessary to fix this problem?

**Comment by leaanthony** [comment]
Good catch. I can fix it 👍

**Pull request merged**
