### PR TITLE
[Documentation]Adding notes for latest linux version and libwebkit issue

### PR DESCRIPTION
**Pull request by pratikmota**
# Description

- For latest linux os(ex: Ubuntu 24.04) libwebkit 4.0 is not supported so wails doctor will give error. We need to install 4.1 version and use tags while building.
- In current Installation documentation these information was not added, I come to know from discord group discussion.
- Given documentation changes will be helpful for community who are using linux.
image
- Issue with 4.0 version
```
sudo apt install libwebkit2gtk-4.0-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libwebkit2gtk-4.0-dev
E: Couldn't find any package by glob 'libwebkit2gtk-4.0-dev'
```
- resolution
1) sudo apt install libwebkit2gtk-4.1-dev
2) wails build  -tags webkit2_41
  
Please delete options that are not relevant.

- [x] This change requires a documentation update

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [ ] Windows
- [x] macOS
- [x] Linux
  
## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.
- As it is only documentation update, wails doctor not needed to test. 
- Adding screenshot for localhost testing
image

# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Bug Fixes**
	- Resolved multiple issues including memory problems, JSON errors, and build issues on macOS and Windows.
	- Fixed drag-and-drop functionality and dialog issues on Windows.

- **Documentation**
	- Updated changelog to reflect version v2.9.2 changes.
	- Enhanced installation documentation for Linux, addressing potential issues with `libwebkit` dependencies and providing solutions for newer distributions.

### CODE REVIEW

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
@pratikmota - Can you please add the changes to the non-versioned documentation please. Thanks 🙏

**Comment by pratikmota** [comment]
> @pratikmota - Can you please add the changes to the non-versioned documentation please. Thanks 🙏

@leaanthony  : I have updated changes in `website/docs/gettingstarted/installation.mdx`
**My understanding:**
- Previously updated changes in below file:
`wails/website/versioned_docs/version-v2.9.0/gettingstarted/installation.mdx `
- As per your comment I need to update same changes to below file. 
`wails/website/docs/gettingstarted/installation.mdx`
Please correct me if i am missing something or not understood properly.
**Doubt:**
Inside i18n languages folder text changes will apply automatically by GitHub Actions. I will not require to change anything right?

**Comment by leaanthony** [comment]
Thank you! 🙏

**Comment by pratikmota** [comment]
@leaanthony : Thank you very much for merge. This was my first contribution in Wails. :-) I will keep contributing this project.

**Pull request merged**
