### PR TITLE
added ytd app to showcase

### PR DESCRIPTION
**Pull request by marcio199226**
Hi I would like to add my app developed within wails to your showcases

### CODE REVIEW

**Comment by leaanthony** [comment]
Really great looking app 👍 could you please remove the yarn file and I'll merge. Thanks 👍

**Comment by leaanthony** [comment]
Do you have any advice for other Angular devs? Would you be interested in writing a short guide? Thanks!

**Comment by marcio199226** [comment]
> Really great looking app +1 could you please remove the yarn file and I'll merge. Thanks +1

OK I will remove it soon. But putting yarn.lock file should be a good practice, isn't it ?

> Do you have any advice for other Angular devs? Would you be interested in writing a short guide? Thanks!

There are some tips I could advice for angular devs developing some app with wails for sure. Do you have something particular in mind? Let's talk about it

**Comment by leaanthony** [comment]
> OK I will remove it soon. But putting yarn.lock file should be a good practice, isn't it ?

Not if it's not related to the change :-)
 
> There are some tips I could advice for angular devs developing some app with wails for sure. Do you have something particular in mind? Let's talk about it

Mainly how you could get a basic app running with Angular. What does your wails.json file look like? How does dev mode work?
 
> Honestly I would like to contribute in some way to your repo

 Would be awesome! 🚀

**Comment by marcio199226** [comment]
Thanks for clean up and approved merge

> Mainly how you could get a basic app running with Angular. What does your wails.json file look like? How does dev mode work?

Sure I could make some mini doc about it, look at the end of this month I have a lot of free time, if you wish I could do some tutorial about guidelines, tips & best practices.

Anyway do you have some internal roadmap with all stuff you will do in the next weeks ? Maybe there are any simple & straight tasks I might do to begin with.

P.S in case you should review my work for english corrections :D

**Comment by leaanthony** [comment]
Mainly Linux support and bug fixes. Will make sure there's tickets made so keep your eye open 🙂

**Pull request merged**
