### PR TITLE
added missing run:darwin task

### PR DESCRIPTION
**Pull request by jpatters**
# Description

Adds a missing run:darwin task. 

Fixes # (issue)

## Type of change
  
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [ ] Windows
- [x] macOS
- [ ] Linux
  
## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tmclane — APPROVED** [review]
Thanks for the PR!

**Comment by leaanthony** [comment]
Thanks 🙏 Please could you add an entry to the changelog located at `mkdocs-website/docs/changelog.md`? Thanks!

**Comment by jpatters** [comment]
> Thanks 🙏 Please could you add an entry to the changelog located at `mkdocs-website/docs/changelog.md`? Thanks!

Will do.

**Review by leaanthony — APPROVED** [review]
Thanks!

**Comment by leaanthony** [comment]
This has now been resolved by just using a `run` command 👍

**Pull request closed without merging**
