### PR TITLE
Add support for Gentoo

### PR DESCRIPTION
**Pull request by fallendusk**
Hi all, new to wails and found that it didn't have support for Gentoo! Tested and working.

### CODE REVIEW

**Comment by bh90210** [comment]
@fallendusk thank you so much for the PR. We are going to look into it asap.

For future reference regarding pull requests please see the documentation: https://wails.app/development/

**Comment by leaanthony** [comment]
Hi @fallendusk. Thanks for the PR! Could you please edit it to be against the develop branch? Thank you! 👍👍

**Comment by leaanthony** [comment]
Hi @fallendusk. I've merged in your PR into version v0.17.2-pre. Please update wails using `wails update -pre` and let me know if there are any issues. Thanks again! 👍

**Comment by leaanthony** [comment]
@fallendusk I'd like to update the main docs to show how to install the Gentoo dependencies. Could you possibly give me a one liner or whatever is needed to do this? Thanks!

**Pull request merged**
