### PR TITLE
V2 Alpha Changes

### PR DESCRIPTION
**Pull request by SGarno**
Ok, I think this is baselined properly now.    Ignore the changes to launch.json.

### CODE REVIEW

**Comment by leaanthony** [comment]
Hey there. This appears to be the same as the PR you closed. Just checking that's what you intended. Regarding the vscode file, if you add it to gitignore thenwe should be good 👍

**Comment by tmclane** [comment]
FYI: I would recommend `rebasing` your branch instead of `merging` it repeatedly.

**Comment by SGarno** [comment]
Strange....I did a fetch upstream and then rebase.   When I did, it said it was already up to date.

**Comment by tmclane** [comment]
Yeah I see that.  Might take a bit of work to resolve this.

**Comment by SGarno** [comment]
Well, I haven't done anything else with this.   I could remove the fork and start over.

**Comment by leaanthony** [comment]
@SGarno - might be worth removing the fork and create a new PR. Before you do though, what circumstances require these changes? I'm running the same codebase on Mac and Windows and have no issues. Cheers 👍

**Pull request closed without merging**
