### PR TITLE
Modified docs to reflect the correct password syntax for the `gon-sign.json` file

### PR DESCRIPTION
**Pull request by ignasbernotas**
# Description

Updates current docs to specify that `@env:*` syntax is no longer supported since Apple has switched to notarytool for signing.

## Type of change

- [x] This change requires a documentation update

## Summary by CodeRabbit

- **New Features**
  - Enhanced dependency management by updating several libraries to their latest versions, potentially improving performance and addressing security issues.

- **Bug Fixes**
  - Added a nil check for the Drag-and-Drop functionality on Windows.
  - Resolved a race condition in the notifyListeners() function, enhancing reliability.

- **Documentation**
  - Updated signing configuration guidelines to reflect the deprecation of Apple's altool syntax and the transition to using the new notarytool.
  - Clarified password syntax for the gon-sign.json file.
  - Made minor fixes for typos in various Markdown files to improve clarity.

### CODE REVIEW

**Comment by leaanthony** [comment]
Thanks 🙏 Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

**Comment by ignasbernotas** [comment]
Sure thing! Will get this sorted this week

**Comment by leaanthony** [comment]
@ignasbernotas - any news? 
Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

**Comment by ignasbernotas** [comment]
@leaanthony sorry for the delay, should be good now. thanks!

**Review by leaanthony — APPROVED** [review]

**Pull request merged**
