### PR TITLE
Remove usage of unsafe.Pointer in winc

### PR DESCRIPTION
**Pull request by leaanthony**
Compiling with `-race` causes a standard windows app to crash. This fixes that. Potential fix for #1554

### CODE REVIEW

**Comment by leaanthony** [comment]
Not sure this is the *correct* fix, but it does fix the problem.

**Comment by stffabi** [comment]
So I think we now return the wrong value.

**Comment by leaanthony** [comment]
@stffabi - yeah, I understand the problem a bit more now. It appears that the use of unsafe pointer and casting to a `*uint16` is how most projects on GitHub do this. Any thoughts?

**Comment by stffabi** [comment]
I think we would need to work with a `uintptr` type instead of a `*uint16`. Which would need some changes on the caller side but I think that might be the only way to satisfy the race detector.

@leaanthony If you would like I could add a proposal to this PR.

**Comment by leaanthony** [comment]
Thanks @stffabi ! I did try changing to uintptr and got reasonably far but it didn't appear to change anything. I was probably doing it wrong

**Comment by stffabi** [comment]
> Thanks @stffabi ! I did try changing to uintptr and got reasonably far but it didn't appear to change anything. I was probably doing it wrong

You have still seen the race error or the missing icon?

**Comment by stffabi** [comment]
I've added a proposal, with this the icon will be displayed correctly. I wasn't able to test the `--race` because it seems like it's not supported on arm64 and I only have Windows ARM64.

**Comment by leaanthony** [comment]
I've just pushed a fix for `EnumProc` which was failing in a similar way.

**Comment by stffabi** [comment]
I think there might be still one edge case, the &monitorContainer pointer should be passed as `unsafe.Pointer` and not uintptr here:

```go
succeeded := w32.EnumDisplayMonitors(dc, nil, syscall.NewCallback(EnumProc), uintptr(unsafe.Pointer(&monitorContainer)))
```

Otherwise go might not now that this pointer is escaping to the syscall and when growing the stack the pointer might get invalid.

**Comment by leaanthony** [comment]
Good catch. I've pushed a commit that I think fixes what you raised. Please review @stffabi  👍

**Review by stffabi — APPROVED** [review]
LGTM

**Comment by stffabi** [comment]
Just for doc purposes, if one needs to just have the checkptr active without `go race` (which needs CGO) one can just use the following flags. 

```sh
go build -gcflags "all=-N -l -d=checkptr"
```

**Pull request merged**
