### PR TITLE
[v3] bugfix: update version to support application.ServiceOptions

### LINKED ISSUE #3835: service template pkg version too old
### Description

The pkg version used by the service template is too old to work properly

### To Reproduce

1. Run `wails3 service init`

### Expected behaviour

1. It will not report an error and run normally
2. use `github.com/wailsapp/wails/v3 v3.0.0-alpha.7`

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
# System
┌──────────────────────────────┐
| Name          | MacOS        |
| Version       | 14.5         |
| ID            | 23F79        |
| Branding      | Sonoma       |
| Platform      | darwin       |
| Architecture  | arm64        |
| Apple Silicon | true         |
| CPU           | Apple M1 Pro |
| CPU           | Unknown      |
| GPU           | Unknown      |
| Memory        | Unknown      |
└──────────────────────────────┘

# Build Environment
┌───────────────────────────────┐
| Wails CLI    | v3.0.0-alpha.7 |
| Go Version   | go1.22.4       |
| -buildmode   | exe            |
| -compiler    | gc             |
| CGO_CFLAGS   |                |
| CGO_CPPFLAGS |                |
| CGO_CXXFLAGS |                |
| CGO_ENABLED  | 1              |
| CGO_LDFLAGS  |                |
| GOARCH       | arm64          |
| GOOS         | darwin         |
└───────────────────────────────┘

# Dependencies
┌────────────────────────────────────────────────────────────────────────┐
| Xcode cli tools | 2408                                                 |
| npm             | 10.8.2                                               |
| *NSIS           | Not Installed. Install with `brew install makensis`. |
└─────────────────────── * - Optional Dependency ────────────────────────┘

# Diagnosis
 SUCCESS  Your system is ready for Wails development!

Need documentation? Run: wails3 docs

 ♥   If Wails is useful to you or your company, please consider sponsoring the project: wails3 sponsor
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by northes**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change
  
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [ ] Windows
- [x] macOS
- [ ] Linux
  
## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

Fixes #3835

## Summary by CodeRabbit

- **Chores**
	- Updated the dependency version for `github.com/wailsapp/wails/v3` to improve stability and performance.
  
- **New Features**
	- Enhanced support for high DPI monitors with a new DIP system.
	- Expanded services for plugin functionality.
	- Introduced templates for SvelteKit and SvelteKit-TS for non-SSR development.
  
- **Bug Fixes**
	- Resolved an issue with the `AlwaysOnTop` functionality on macOS.
	- Fixed drag-and-drop functionality and compile errors on Linux.
	- Addressed system tray startup issues on Windows.
	- Corrected a duplicate `PasteAndMatchStyle` role in the edit menu on Darwin.

### CODE REVIEW

**Comment by leaanthony** [comment]
Thanks 🙏 Please could you add an entry to the changelog located at `mkdocs-website/docs/changelog.md`? Thanks!

**Comment by northes** [comment]
> Thanks 🙏 Please could you add an entry to the changelog located at `mkdocs-website/docs/changelog.md`? Thanks!

`mkdocs-website/docs/Changelog.md` does not seem to have no entry of` v3.0.0-alpha.8`, should I add it, or wait for it later?

**Comment by northes** [comment]
> Thanks 🙏 Please could you add an entry to the changelog located at `mkdocs-website/docs/changelog.md`? Thanks!

I am honored to participate in it. 😎 I have updated it.

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Thanks for this! 🙏

**Pull request merged**
