### PR TITLE
Set bundlename for single targets

### PR DESCRIPTION
**Pull request by leaanthony**
Another attempt at fixing the bundle output for Mac @Snider @gwynforthewyn

### CODE REVIEW

**Comment by gwynforthewyn** [comment]
@leaanthony , where are you getting the output from that's guiding this ongoing change?

**Comment by leaanthony** [comment]
I reread the original issue which stated that the problem was in the bundle name, so I looked at the packaging code and sure enough, it's hardwired to the name of the project.

**Comment by gwynforthewyn** [comment]
@leaanthony  ah! Thank you! I had asked in https://github.com/wailsapp/wails/issues/2290#issuecomment-1422036611 about addressing the CFBundleName,  but it was brought in as part of a conversation about whether I should also update the window title and then the bundle name got lost as a detail in that other conversation. 

Let me know if you want me to take a look through the whole plist file to see if there are any other pieces of metadata to update; I'm not 100% sure if you'd like that  stand with the next revision of the wails cli including a change to the build system

**Comment by leaanthony** [comment]
If @Snider can confirm this is working then I'm happy to merge and release 2.4

**Comment by stffabi** [comment]
Seems like specifying the `-o` flag doesn't have an effect anymore. Was this an intended change? I thought that we fixed that with another PR.

**Comment by leaanthony** [comment]
The intent was the opposite :-) `-o` is ignored for the bundle name :(

**Pull request closed without merging**
