### PR TITLE
[windows] Support drawing a frame for frameless to support hiding the titlebar

### LINKED ISSUE #990: [v2] Windows: Support a window without titlebar but with a border
**Is your feature request related to a problem? Please describe.**
It would be awesome to have support for a window just without a titlebar but with a border. Sometimes one want's just to have a hidden titlebar but still have a border around the window. This is especially interesting if the background of the frontend is mostly white.

**Describe the solution you'd like**
A flag to enable drawing a border for windows if frameless is active or some other kind of configuration options to achieve this.

### PR DESCRIPTION
**Pull request by stffabi**
Idea to fix #990

### CODE REVIEW

**Comment by leaanthony** [comment]
This is great. We can migrate to top level config if the other platforms support it. do you think you could include a doc update in this pr? I want to try and keep the site up to date with PRs. If not I can do it later. Many thanks 🙏

**Comment by stffabi** [comment]
Yes I can adjust the docs, I've just seen that they are on the top level of the repo. I was searching in the v2 folder before... I'll update it tomorrow, because it's getting quite late here 😄

**Comment by stffabi** [comment]
I've added the docs.

**Comment by stffabi** [comment]
Thanks for merging.

**Pull request merged**
