### PR TITLE
[v3] add typesafe model source to template

### PR DESCRIPTION
**Pull request by dominictwlee**
As mentioned in #2548, this is an attempt to narrow source type to match model fields.

@leaanthony let me know what you think.

### CODE REVIEW

**Comment by leaanthony** [comment]
Thanks for looking at this. So this is an attempt to allow a Partial to populate an object rather than a string? I think I'd need someone more familiar with TS to review this. I'll ask on the discord server 👍

**Comment by plihelix** [comment]
The problem is mostly because of type limits when going from go -> json -> ts.


From what I can tell, if the generated models encounter a type that isn't generated it will parse the JSON just fine (into any type) but will fail to convert due to the 'null' type being passed into the conversion function. 

Rather than a null, this should stay as any (#1) and the 'asMap' flag should be set to true #2 so that it is converted to a map instead of discarded.

```ts
// example generated models.ts
export class Person {
	name: string;
	// Go type: iso8601    <- Correctly identified type not  defined and generated
	born: any;              // <- 'any' type for JSON parsing
        ...
	
	constructor(source: any = {}) {
	    if ('string' === typeof source) source = JSON.parse(source);  <- Parse JSON input
	    this.name = source["name"];
	    this.born = this.convertValues(source["born"], null);                <- #1 defaults to null
	    ...
	}
	
        // Generic conversion function that is used in the constructor.
        // Given the source any and the target type convert the JSON into
        // the appropriate TS type. 
        // Optionally return a k:v pair map for unknown data.
        convertValues(a: any, classs: any, asMap: boolean = false): any {
	    if (!a) {
	        return a;
            }
	    if (a.slice) {
	        return (a as any[]).map(elem => this.convertValues(elem, classs));
	    } else if ("object" === typeof a) {
	        if (asMap) {                                                                          <- #2 returns a pair map of the json
	            for (const key of Object.keys(a)) {
	                a[key] = new classs(a[key]);
	            }
	            return a;
	        }
	        return new classs(a);                                                 <- pushing a value into a null gets a null
	    }
	    return a;
	}
}
```

**Comment by dominictwlee** [comment]
> Thanks for looking at this. So this is an attempt to allow a Partial to populate an object rather than a string? I think I'd need someone more familiar with TS to review this. I'll ask on the discord server 👍

Yeah. This is a case of making things a bit more convenient when initializing a model.

i.e.
```
const person = new Person({
  name: 'hello'; // typed as name: string, typescript won't show an error
   buddy: 123 // doesn't exist in source type, will show a TS error
})
```

**Comment by leaanthony** [comment]
Necromancing this as this is something we are looking at in the current v3 alpha. IF you'd like to join in on the discussion, feel free to join us [here](https://discord.com/channels/1042734330029547630/1184977285225398393).

**Pull request closed without merging**
