### PR TITLE
v2 [#3133] SingleInstanceData: Fill missing WD as is

### LINKED ISSUE #3133: v2 linux: SecondInstanceData.WorkingDirectory not initialized
### Description

v2.7 instoduced `SingleInstanceLock`, but on linux the `SecondInstanceData.WorkingDirectory` is always empty:

https://github.com/wailsapp/wails/blob/dc5f0b6e7bc6d21d3eeb88f65b77423e85256fb7/v2/internal/frontend/desktop/linux/single_instance.go#L55-L57

### To Reproduce

```go
func (a *App) secondInstance(data options.SecondInstanceData) {
	runtime.LogInfof(a.ctx, "%#v", data)
}
```
```sh
$ ./build/bin/linux-app ../foo.txt
```

### Expected behaviour

```
INF | options.SecondInstanceData{Args:[]string{"../foo.txt"}, WorkingDirectory:"/abs/path"}
```

### Screenshots

```
INF | options.SecondInstanceData{Args:[]string{"../foo.txt"}, WorkingDirectory:""}
```

### Attempted Fixes

_No response_

### System Details

```shell
# Wails
Version         | v2.7.1
Package Manager | apt   

# System
┌──────────────────────────────────────────────────────────────────────────────────┐
| OS           | Ubuntu                                                            |
| Version      | 22.04                                                             |
| ID           | ubuntu                                                            |
| Go Version   | go1.20.5                                                          |
| Platform     | linux                                                             |
| Architecture | amd64                                                             |
| CPU          | AMD Ryzen ...
| GPU          | unknown (Advanced Micro Devices, Inc. [AMD/ATI]) - Driver: amdgpu |
| Memory       | ..GB                                                              |
└──────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌──────────────────────────────────────────────────────────────────────────┐
| Dependency | Package Name          | Status    | Version                 |
| *docker    | docker.io             | Available | 24.0.5-0ubuntu1~22.04.1 |
| gcc        | build-essential       | Installed | 12.9ubuntu3             |
| libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2        |
| libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.42.3-0ubuntu0.22.04.1 |
| npm        | npm                   | Installed | 9.5.1                   |
| *nsis      | nsis                  | Installed | v3.08-2                 |
| pkg-config | pkg-config            | Installed | 0.29.2                  |
└──────────────────────── * - Optional Dependency ─────────────────────────┘

# Diagnosis
Optional package(s) installation details: 
  - docker: sudo apt install docker.io

 SUCCESS  Your system is ready for Wails development!
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Vovan-VE**
# Description

Minimal fix for missing `WorkingDirectory` for linux and windows.

Fixes #3133

## Type of change
  
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested locally in my wails app by replacing wails repo to local forked repo. Worked fine under linux and windows. Darwin was not changed and I cannot test it.

go.mod
```
replace github.com/wailsapp/wails/v2 => ../wails/v2
```
app.go
```go
func (a *App) secondInstance(data options.SecondInstanceData) {
	runtime.LogInfof(a.ctx, "%#v", data)
}
```

**linux**
```sh
[/abs/path]$ ./app ../../path/file.txt ../foo/bar.txt
```
first instance output
```
INF | options.SecondInstanceData{Args:[]string{"../../path/file.txt", "../foo/bar.txt"}, WorkingDirectory:"/abs/path"}
```

**windows**
```
C:\abs\path> app.exe ..\..\path\file.txt ..\foo\bar.txt
```
first instance output
```
INF | options.SecondInstanceData{Args:[]string{"..\\..\\path\\file.txt", "..\\foo\\bar.txt"}, WorkingDirectory:"C:\\abs\\path"}
```

- [x] Windows
- [x] Linux
  
## Test Configuration

Still same as in #3133

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Bug Fixes**
  - Fixed uninitialized `SecondInstanceData.WorkingDirectory` on Linux and Windows.

### CODE REVIEW

**Comment by Vovan-VE** [comment]
@APshenkin

**Comment by leaanthony** [comment]
Thanks 🙏 Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

**Comment by Vovan-VE** [comment]
I skipped that `err` checks just in the same style as the local code style there.

**Review by leaanthony — APPROVED** [review]
Thanks so much for this 🙏

**Comment by APshenkin** [comment]
@Vovan-VE sorry, that didn't looked at this earlier, holidays knocked me away from the laptop 😅

Thank you for fixing this!

**Pull request merged**
