### PR TITLE
Allow to specify macos-min-version externally

### PR DESCRIPTION
**Pull request by APshenkin**
# Description
Wails setup `mmacosx-version-min` while building the app. However there could be the cases, when developers want to specify higher min version. Currently it's not possible, cause latest `mmacosx-version-min` is taken as priority

Fixes # (issue)

## Type of change
  
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [ ] Windows
- [x] macOS
- [ ] Linux
  
## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Added the ability to specify the minimum macOS version externally in project configuration.
- **Bug Fixes**
	- Improved command generation by preventing duplication of the macOS version flag, enhancing execution reliability.
	- Fixed memory issues on Darwin.
	- Enhanced JSON compatibility for author names.
	- Improved handling of file drop events on Windows.
- **Documentation**
	- Added a new section in CLI documentation for setting a minimal version for macOS applications.
	- Introduced information regarding UPX on Apple Silicon in the CLI documentation.
	- Updated documentation to indicate that `ZoomFactor` and `IsZoomControlEnabled` options are now Windows-only.

### CODE REVIEW

**Review by leaanthony — CHANGES_REQUESTED** [review]
Could you please update the documentation? Thank you 🙏

**Comment by APshenkin** [comment]
@leaanthony missed your comment, sorry for delay.

I added note in documentation for this

**Review by leaanthony — APPROVED** [review]

**Comment by APshenkin** [comment]
@leaanthony not sure why, but some mandatory checks for tests don't run. Should them been triggered somehow?

**Comment by leaanthony** [comment]
Thanks again @APshenkin 🙏

**Pull request merged**
