### PR TITLE
feat(website): optimize and sync websites and documents

### PR DESCRIPTION
**Pull request by misitebao**
- Optimize website terminology
- Optimized English documentation
- Sync Chinese documents
- Added vscode style unified configuration

### CODE REVIEW

**Comment by leaanthony** [comment]
This is great @misitebao! Thanks! Do we need to update `package-lock.json`?

**Comment by misitebao** [comment]
@leaanthony 
This is just an automatic update based on the version number rule after I execute `npm install`, and it has no effect on the application.

**Comment by leaanthony** [comment]
Thanks for clarifying. Can you please remove it as I'm going to update the dependencies separately. Thanks!

**Comment by misitebao** [comment]
> Thanks for clarifying. Can you please remove it as I'm going to update the dependencies separately. Thanks!

Has been rolled back.

**Pull request merged**
