### PR TITLE
New CI

### PR DESCRIPTION
**Pull request by bh90210**
I replaced `azure pipelines` with `github actions` mainly cause azure seems to never work as expected (see badge on README).
plus having github's "native" CI makes the whole thing more easily maintainable for contributors. 

The way new CI works atm is a test build (`wails version`) on:
* master branch push
* tag with `pre` in it for -pre releases
* pull request on develop branch

two things to research:
1. in the CI of master releases maybe it is possible/desirable to automate npm repo push https://www.npmjs.com/~wailsapp
2. after each pre-release have the CI update a part of the website with latest features/instructions in an effort to keep the website alive & healthy. 

EDIT:
future badges will be available like this
```
![](https://github.com/wailsapp/wails/workflows/release/badge.svg?branch=master)
![](https://github.com/wailsapp/wails/workflows/pr/badge.svg?branch=develop)
![](https://github.com/wailsapp/wails/workflows/latest-pre/badge.svg?branch=master)
```

EDIT2:
one more meaningful update would be to also `wails build` and test against a matrix of node's versions

### CODE REVIEW

**Comment by leaanthony** [comment]
This is amazing @bh90210! I agree with everything above. I think a push to the website would be good. How do we get cross-repo pushes though? Or are you suggesting we pull the docs into this repo. The only reason I've been against that is download size of modules, but maybe nobody cares?

**Comment by bh90210** [comment]
hmm I am thinking of 
checking out `wailsapp/docs` in the CI > generate/commit everything > push to docs repo > another pipeline picks up from there and makes a deployment

**Comment by bh90210** [comment]
before anything else we could start with a sensible whenever there is a pre tag to update the website with this information?

**Comment by leaanthony** [comment]
I'm happy to test it for sure.

**Pull request merged**
