### PR TITLE
Better support for reloading using wails dev

### PR DESCRIPTION
**Pull request by leaanthony**
Show error instead of crashing. Potential to do exponential backoff...?

### CODE REVIEW

**Comment by leaanthony** [comment]
@misitebao

**Comment by misitebao** [comment]
@leaanthony 
the problem still exists.😭
image

**Comment by leaanthony** [comment]
Based on your screenshot, it looks like your project isn't using the local source. Those line numbers are the old ones.

**Comment by misitebao** [comment]
> 根据您的屏幕截图，您的项目似乎没有使用本地源。这些行号是旧的行号。



> Based on your screenshot, it looks like your project isn't using the local source. Those line numbers are the old ones.

I'm sure I'm using the latest code.

**Comment by misitebao** [comment]
This branch code has errors.
image

**Comment by leaanthony** [comment]
If you merge locally, does this PR work?

**Comment by leaanthony** [comment]
@misitebao Pushed more commits to try something new....

**Comment by misitebao** [comment]
@leaanthony 
image

**Comment by leaanthony** [comment]
I don't think that error has anything to do with the PR ☝️

**Comment by leaanthony** [comment]
This issue will go away once #1283 gets merged.

**Pull request closed without merging**
