### PR TITLE
Add option to disable window re-focus when go app reloads

### PR DESCRIPTION
**Pull request by birdmanmandbir**
This PR adds option to disable window re-focus when go app reloads. https://github.com/wailsapp/wails/issues/1495 

## Application options
I created a new property in the App options, It defaults to false

## How to test
- [x] with `NoDesktopOnDev: true`, run `wails dev` not open the desktop app and http://localhost:34115 have normal behavior
- [x] with `NoDesktopOnDev: true`, run `wails build`, the executable have normal behavior
- [x] with `NoDesktopOnDev: false`, run `wails dev`  open the desktop app

Current functionality is working. I also wrote the documentation for En and Zh-Hans.

Below is an example main.go file that can be used as a test in a clean wails project
```go
package main

import (
	"embed"

	"github.com/wailsapp/wails/v2"
	"github.com/wailsapp/wails/v2/pkg/options"
	"github.com/wailsapp/wails/v2/pkg/options/assetserver"
)

//go:embed all:frontend/dist
var assets embed.FS

func main() {
	// Create an instance of the app structure
	app := NewApp()

	// Create application with options
	err := wails.Run(&options.App{
		Title:  "wails-vue",
		Width:  1024,
		Height: 768,
		AssetServer: &assetserver.Options{
			Assets: assets,
		},
		BackgroundColour: &options.RGBA{R: 27, G: 38, B: 54, A: 1},
		OnStartup:        app.startup,
		Bind: []interface{}{
			app,
		},
		Debug: options.Debug{
			StartHiddenOnDev: true,
		},
	})

	if err != nil {
		println("Error1:", err.Error())
	}
}

```
@leaanthony

### CODE REVIEW

**Comment by leaanthony** [comment]
You may be able to get the same functionality if you set `StartHidden: true` in your application options?

**Comment by birdmanmandbir** [comment]
> You may be able to get the same functionality if you set `StartHidden: true` in your application options?

I have try it, but with `StartHidden: true`, The window will also hidden in production mode after `wails build`, but I only want to hidden in dev mode, and It's easy to forget to remove the option when `wails build`

**Comment by stffabi** [comment]
Maybe you could add a flag that overrides the 'StartHidden' to the debug options in the appoptions?

**Comment by birdmanmandbir** [comment]
> Maybe you could add a flag that overrides the 'StartHidden' to the debug options in the appoptions?

You are right, I have moved it to `Debug.StartHiddenOnDev`

**Comment by leaanthony** [comment]
I see this as more a cli flag because as you said, it's easy to forget it when you build. I'm going to add this to v3. Feel free to use a fork of v2 with this patch until it's released.

**Pull request closed without merging**
