### PR TITLE
If the element adds the data-rails-drag attribute, it can trigger the…

### PR DESCRIPTION
**Pull request by jicg**
… dbclick event.

### CODE REVIEW

**Comment by leaanthony** [comment]
Thanks for doing this. What platforms did you test on?

**Comment by jicg** [comment]
i test on `Windows 10 Pro , Version: 2009 (Build: 19042)` and `MacOS 11.0.1` .

**Comment by leaanthony** [comment]
@kiddov you might be interested in this 👍

**Review by KiddoV — CHANGES_REQUESTED** [review]
Hmmm.... Double click still doing nothing on my site.

**Comment by leaanthony** [comment]
I'm going to pull this in and make a couple of changes. Thanks @jicg for getting this started 👍

**Comment by leaanthony** [comment]
@KiddoV - I've updated master with the updated runtimes. Setting up a dblclick handler works for me, EG:
`window.ondblclick = function() { console.log("DBL CLICK!"); }`

**Comment by KiddoV** [comment]
@leaanthony Do I need to add a double click event to the ``data-wails-drag`` or something?

**Comment by leaanthony** [comment]
I added it to window to test but I imagine it's work on the element too

**Comment by KiddoV** [comment]
Idk. When I double click on the ``data-wails-drag``, it's still doing nothing 🤷🏻‍♂️.

**Pull request merged**
