### PR TITLE
[V3 Linux] aarch64 compilation

### LINKED ISSUE #3: Support bundle for Windows
We need to support 'wails bundle' for Windows. [Potential solution](https://github.com/akavel/rsrc).

### LINKED ISSUE #3840: [V3 Linux] aarch64 compilation not working
### Description

I would like to create linux app for arm64 or x86_64

### To Reproduce

Task package on arm64 Linux

### Expected behaviour

I expect to create an app for aarch64

### Screenshots

_No response_

### Attempted Fixes

I create a pull request to fix them: i would like to be a contributor https://github.com/kodflow/wails/pull/3/files

### System Details

```shell
┌───────────────────────────────────────────┐
| Name         | Ubuntu                     |
| Version      | 24.04                      |
| ID           | ubuntu                     |
| Branding     | 24.04.1 LTS (Noble Numbat) |
| Platform     | linux                      |
| Architecture | arm64                      |
| CPU          |                            |
| Memory       | 7GB                        |
└───────────────────────────────────────────┘

# Build Environment
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| Wails CLI      | v3.0.0-alpha.7                                                                                                            |
| Go Version     | go1.23.2                                                                                                                  |
| -buildmode     | exe                                                                                                                       |
| -compiler      | gc                                                                                                                        |
| CGO_ENABLED    | 0                                                                                                                         |
| DefaultGODEBUG | asynctimerchan=1,gotypesalias=0,httpservecontentkeepheaders=1,tls3des=1,tlskyber=0,x509keypairleaf=0,x509negativeserial=1 |
| GOARCH         | arm64                                                                                                                     |
| GOARM64        | v8.0                                                                                                                      |
| GOOS           | linux                                                                                                                     |
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌──────────────────────────────────────┐
| pkg-config | 1.8.1-2build1           |
| webkit2gtk | 2.44.3-0ubuntu0.24.04.1 |
| gcc        | 12.10ubuntu1            |
| gtk3       | 3.24.41-4ubuntu1.2      |
| npm        | 9.2.0                   |
└────── * - Optional Dependency ───────┘
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kodflow**
# Description

This pull request addresses an issue in the `v3/internal/commands/appimage.go` file, where the logic to generate AppImages was not functioning correctly on certain platforms. The modification ensures that the `appimage.go` command correctly handles the generation of AppImages for Linux environments by updating the build process.

Fixes #3840 

## Type of change
  
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
  
The fix was tested by building the project on different Linux distributions and verifying that the AppImage generation now works correctly. Additional logging was added to confirm that all steps in the process are successfully executed.

- [x] Linux

## Summary by CodeRabbit

- **New Features**
	- Enhanced application image generation with architecture-specific handling for `arm64` and `x86_64`.
	- Improved download process for necessary files with architecture-specific URLs for concurrent downloads.
	- Added a new command for updating build assets.
	- Introduced templates for SvelteKit and SvelteKit-TS for non-SSR development.
	- Added an example for testing the HTML Drag and Drop API.
	- New command added: `wails3 generate runtime`.

- **Bug Fixes**
	- Resolved `AlwaysOnTop` functionality on macOS.
	- Addressed a duplicate role in the edit menu for Darwin systems.
	- Fixed aarch64 compilation issues on Linux.
	- Fixed custom event processing in drag-and-drop examples.
	- Corrected syso icon file generation bugs on Windows.

- **Refactor**
	- Simplified GTK version determination logic for better clarity.
	- Updated the Taskfile and improved CI actions.
	- Consolidated development configuration into `config.yml`.

### CODE REVIEW

**Comment by leaanthony** [comment]
Thanks 🙏 Please could you add an entry to the changelog located at `mkdocs-website/docs/changelog.md`? Thanks!

**Comment by kodflow** [comment]
> Thanks 🙏 Please could you add an entry to the changelog located at `mkdocs-website/docs/changelog.md`? Thanks!

done

**Comment by leaanthony** [comment]
@atterpac - you good with this change?

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Thanks so much for doing this @kodflow 🙏

**Pull request merged**
