### PR TITLE
Modify options ZoomFactor and IsZoomControlEnabled to windows only…

### LINKED ISSUE #3643: IsZoomControlEnabled and ZoomFactor are windows only options
### Have you read the Documentation Contribution Guidelines?

- [X] I have read the [Documentation Contribution Guidelines](https://wails.io/community-guide#ways-of-contributing).

### Description

`IsZoomControlEnabled` and `ZoomFactor` are windows only options, not public options

### Self-service

- [X] I'd be willing to address this documentation request myself.

### PR DESCRIPTION
**Pull request by levinit**
# Description

IsZoomControlEnabled and ZoomFactor are windows only options.

Fixes #3643 #3191

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [ ] Windows
- [ ] macOS
- [ ] Linux
  
## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [ ] My code follows the general coding style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **Documentation**
	- Reorganized documentation for `ZoomFactor` and `IsZoomControlEnabled` options across multiple language references to enhance clarity and accessibility.
	- Improved logical flow by repositioning zoom-related information to better align with user needs.
	- Maintained existing definitions and functionalities for all options.
	- Updated changelog to clarify that `ZoomFactor` and `IsZoomControlEnabled` are now Windows-only features, affecting users on other operating systems.

### CODE REVIEW

**Comment by levinit** [comment]
I am sorry there are 2 `to` in the commit msg  😢

**Comment by leaanthony** [comment]
Thanks 🙏 Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

**Comment by levinit** [comment]
> Thanks 🙏 Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

I have modified the `changelog.mdx`, please check it, are there any other issues?

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Thank you @levinit 🙏

**Pull request merged**
