### PR TITLE
Move watcher init to doWatcherLoop and implement -reloaddirs

### LINKED ISSUE #2829: `-reloaddirs` option does not work
### Description

When using the `-reloaddirs` option to specify a folder outside the working directory, the app is not reloaded when any files in those folders change

### To Reproduce

1. `mkdir -p /tmp/myproject/common`
2. `cd /tmp/myproject && go work init`
4. `wails init -n gui -t preact-ts`
5. `go work use gui`
7. `cd common && go mod init myproject/common`
8. `go work use .`
9. `touch foo.go`
10. copy the following to `foo.go`
    ```go
    package common
    
    import "fmt"
   
    func doSomething() {
	    fmt.Println("Something else")
    }
    ```
11. `cd /tmp/myproject/gui`
12. `wails dev -reloaddirs=/tmp/myproject/common`
13. In a different process, make changes to `/tmp/myproject/common/foo.go`

### Expected behaviour

Changes made to `/tmp/myproject/common/foo.go` should have caused the watcher to reload, but instead nothing happens

### Screenshots

_No response_

### Attempted Fixes

I've tried specifying the `reloaddirs` option in many ways, but none of them works. I believe the problem is that the variable which contains `dirsThatTriggerAReload`, found here: https://github.com/wailsapp/wails/blob/7fae22b50ceaa4750663f2289957dee0a1f5bdb9/v2/cmd/wails/internal/dev/dev.go#L339-L343

is not being added to the watcher, therefore none of the changes specified by `-reloaddirs` option are being detected

### System Details

```shell
Wails CLI v2.5.1

# System

OS           | ArcoLinux
Version      | Unknown  
ID           | arcolinux
Go Version   | go1.20.5 
Platform     | linux    
Architecture | amd64    

# Wails

Version         | v2.5.1
Package Manager | pacman

# Dependencies

Dependency | Package Name | Status    | Version    
*docker    | docker       | Installed | 1:24.0.5-1 
gcc        | gcc          | Installed | 13.2.1-3   
libgtk-3   | gtk3         | Installed | 1:3.24.38-1
libwebkit  | webkit2gtk   | Installed | 2.40.5-1   
npm        | npm          | Installed | 9.8.1-1    
pkg-config | pkgconf      | Installed | 1.8.1-1    
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by haukened**
# Description

In investigating #2829 i found that the `*fsnotify.Watcher` was only passed to a single function `doWatcherLoop` but the `f.ReloadDirs` wasn't parsed until inside the `doWatcherLoop`.  

This PR moves the definition into `doWatcherLoop` to prevent unnecessary passing of the object, and implemented adding the `-reloaddirs` flag to the watcher.  To prevent over-subscribing the watcher, i made the intentional choice not to make the watch recursive (like the main folder is), instead opting to explicitly watch only the directories specified by the user.

Fixes #2829 

## Type of change
  
Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
  
Tested using the steps outlined in #2829 to confirm resolution:
>Output noted that the directory was being watched:
>```
>Using DevServer URL: http://localhost:34115
>Using Frontend DevServer URL: http://localhost:5173/
>Using reload debounce setting of 100 milliseconds
>Watching (sub)/directory: /tmp/myproject/gui
>Watching (sub)/directory: /tmp/myproject/common
>```

>`wails-dev` binary built from source noticed the change in outside directory, and restarted:
>```
>[Rebuild triggered] files updated
>  • Generating bindings: 
>Done.
>>  • Compiling application: 
>```

- [ ] Windows
- [ ] macOS
- [X] Linux
  
## Test Configuration

```
╭─david@arch /tmp/myproject/common  
╰─➤  wails doctor
Wails CLI v2.5.1

 SUCCESS  Done.                                                                                                                                             

# System

OS           | Arch Linux
Version      | Unknown   
ID           | arch      
Go Version   | go1.21.0  
Platform     | linux     
Architecture | amd64     

# Wails

Version         | v2.5.1
Package Manager | pacman

# Dependencies

Dependency | Package Name | Status    | Version    
*docker    | docker       | Installed | 1:24.0.5-1 
gcc        | gcc          | Installed | 13.2.1-3   
libgtk-3   | gtk3         | Installed | 1:3.24.38-1
libwebkit  | webkit2gtk   | Installed | 2.40.5-1   
npm        | npm          | Installed | 9.8.1-1    
pkg-config | pkgconf      | Installed | 1.8.1-1    
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
```

# Checklist:

- [X] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [X] My code follows the general coding style of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by leaanthony** [comment]
@haukened - Any chance you could fix the conflict? Your other PR caused it 😅

**Comment by haukened** [comment]
> @haukened - Any chance you could fix the conflict? Your other PR caused it 😅

Nothing like conflicts in the changelog! 😂😂

**Comment by haukened** [comment]
@leaanthony good to go now

**Review by leaanthony — APPROVED** [review]
Thanks for this! 🙏

**Pull request merged**
