### PR TITLE
[assetserver] Add support for serving the index.html file when requesting a directory

### LINKED ISSUE #2109: Dev build uses ExternalAssetHandler, but production build does not?
### Description

When I run `wails dev` and my frontend navigates to `/gallery/`, my external assets handler rewrites the request to serve `/gallery/index.html`. However, with the exact same code compiled with `wails build`, the exact same page load yields 500 Internal Server Error.

### To Reproduce

Here's my code:

```
func (a *App) Run() error {
	return wails.Run(&options.App{
		Title:     "Timelinize",
		Width:     1200,
		Height:    800,
		Frameless: true,
		AssetServer: &assetserver.Options{
			Assets:     a.frontend,
			Middleware: a.StaticWebsiteMiddleware,
		},
		OnStartup: func(ctx context.Context) { a.ctx = ctx },
		Bind:      []any{a},
	})
}
```

Notice I set up a custom AssetServer with my own Middleware. The Middleware basically determines whether the request needs to be rewritten or have server-side templates evaluated, and if not, it passes the request to the next handler (wails).

Anyway, this all works great with `wails dev`:

```
DEB | [ExternalAssetHandler] Loading 'http://localhost:3000/gallery/'
```

But running the same program from `wails build` produces:

```
ERR | [AssetHandler] Unable to load file 'gallery/': open gallery/: invalid argument
```

It seems to me that the production build is not using ExternalAssetHandler.

### Expected behaviour

I'd expect `wails dev` and `wails build` programs to run the same in this regard.

### Screenshots

(Probably not applicable, since it's text logs. The UI just crashes with "Internal server error" 

### Attempted Fixes

I'm not sure what to try yet. This is a new feature, so I'm not surprised if I'm either using it wrong or there's a little bug. :bug: :slightly_smiling_face: 

### System Details

```shell
Wails CLI v2.2.0

Scanning system - Please wait (this may take a long time)...Done.

System
------
OS:             Pop!_OS
Version:        22.04
ID:             pop
Go Version:     go1.19.1
Platform:       linux
Architecture:   amd64

Wails
------
Version:                v2.2.0
Package Manager:        apt

Dependency      Package Name            Status          Version
----------      ------------            ------          -------
*docker         docker.io               Available       20.10.12-0ubuntu4
gcc             build-essential         Installed       11.3.0
libgtk-3        libgtk-3-dev            Installed       3.24.33-1ubuntu2
libwebkit       libwebkit2gtk-4.0-dev   Installed       2.38.2-0ubuntu0.22.04.2
npm             npm                     Installed       8.5.1~ds-1
*nsis           nsis                    Available       3.08-2
pkg-config      pkg-config              Installed       0.29.2

* - Optional Dependency

Diagnosis
---------
Your system is ready for Wails development!
Optional package(s) installation details: 
  - docker: sudo apt install docker.io
  - nsis: sudo apt install nsis
```

### Additional context

Thank you again for Wails, it's awesome!

### PR DESCRIPTION
**Pull request by stffabi**
Furthermore this PR improves some error messages for the AssetServer Options and adds some additional checks. 

Fixes #2109

### CODE REVIEW

**Comment by mholt** [comment]
Ohh, very nice. I'll give this a try!

**Comment by stffabi** [comment]
@mholt Just wanted to ask if you eventually found time to give this a try?

**Comment by mholt** [comment]
@stffabi Sorry for the wait! :sweat: I haven't been available much with the holiday and such this week. Thanksgiving is a very big day in the US that disrupts nearly the whole week. I'll try to look at this soon. (Don't wait on me though, if you want to merge it in sooner, I don't want to be a blocker.)

**Comment by stffabi** [comment]
I’m sorry, I really didn’t want to stress you.
Hope you had a wonderful time with your beloved ones.

**Comment by leaanthony** [comment]
Thanks for doing this - this is great! I'm going to open a new ticket that I'll do after this has been merged to update the default `index.html` page with better information on why it is being shown and how to fix it 👍

**Review by leaanthony — APPROVED** [review]

**Comment by stffabi** [comment]
Thanks for approving 🙏

**Comment by mholt** [comment]
Thank you again for doing this :) I am hoping to catch up to it this week!

Really appreciate all you both do to work on this project :pray:

**Pull request merged**
