### PR TITLE
[v3] Fix ordering of if branches in WebviewWindow.Restore method

### PR DESCRIPTION
**Pull request by fbbdev**
# Description

The Window.Restore method currently checks first whether the window is maximised, in which case it calls UnMaximise and returns, otherwise it proceeds to check whether it is in fullscreen mode or minimised.

This behaviour is both buggy and conceptually wrong:
  - conceptually, it is possible for a window to be both maximised and in fullscreen mode, and typically fullscreen mode will have been entered *after* the window was maximised, hence the intuitive behaviour is to exit fullscreen first;
  - practically, this results in a bug on macOS where restore *does nothing* in fullscreen mode, as it seems that the macOS windowing backend treats all fullscreen windows as also maximised.

Swapping the order of the branches fixes the problem on macOS.

To reproduce (on macOS):
  - clone the [PR branch](https://github.com/fbbdev/wails/tree/fix-restore),
  - checkout the [second-last commit](https://github.com/fbbdev/wails/commit/3020b0a2f085cd2197bdfa04b50e8e00e8d6d69b) (`git checkout 3020b0a2f08`),
  - run the new [`window-api` example](https://github.com/fbbdev/wails/tree/fix-restore/v3/examples/window-api),
  - click the 'Fullscreen' button, then the 'Restore' button: nothing will happen.

## Type of change
  
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I created the [`window-api` example](https://github.com/fbbdev/wails/tree/fix-restore/v3/examples/window-api) and used it to test most relevant combinations (maximise-then-restore, fullscreen-then-restore). I have not tested minimise-then-restore.

- [ ] Windows
- [x] macOS
- [ ] Linux
  
## Test Configuration

```# Build Environment
Wails CLI      | v3.0.0-alpha.3                                                                
Go Version     | go1.22.0                                                                      
Revision       | 12d12a33dec1d31f487b70f87bc31e80252f327c                                      
Modified       | true                                                                          
-buildmode     | exe                                                                           
-compiler      | gc                                                                            
CGO_CFLAGS     |                                                                               
CGO_CPPFLAGS   |                                                                               
CGO_CXXFLAGS   |                                                                               
CGO_ENABLED    | 1                                                                             
CGO_LDFLAGS    |                                                                               
DefaultGODEBUG | httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
GOAMD64        | v1                                                                            
GOARCH         | amd64                                                                         
GOOS           | darwin                                                                        
vcs            | git                                                                           
vcs.modified   | true                                                                          
vcs.revision   | 12d12a33dec1d31f487b70f87bc31e80252f327c                                      
vcs.time       | 2024-02-21T12:40:32Z                                                          

# System
Name            | MacOS                                   
Version         | 12.6.6                                  
ID              | 21G646                                  
Branding        | Monterey                                
Platform        | darwin                                  
Architecture    | amd64                                   
Apple Silicon   | unknown                                 
CPU             | Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Xcode cli tools | 2395                                    
CPU             | Unknown                                 
GPU             | Unknown                                 
Memory          | Unknown                                 

# Diagnosis
 SUCCESS  Your system is ready for Wails development!
```

# Checklist:

- [x] I have updated `mkdocs-website/docs/en/changelog.md` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (N/A)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by leaanthony** [comment]
Not sure if I'm doing something wrong here but clicking restore when in fullscreen doesn't unfullscreen it... I wonder what I'm doing wrong 🤔

**Comment by fbbdev** [comment]
I am gonna clone the branch and test it again from a clean slate, let's see what happens

**Comment by fbbdev** [comment]
I've done the tests, here's what I see:

- repo at `fix-restore`, working tree clean, working dir is `v3`
- `git checkout 3020b0a2f085cd`
- `go clean . && go clean -cache`
- `cd examples/window-api`
- `go run .` –> long build time –> the restore button **does nothing** in fullscreen
- `git checkout fix-restore`
- `go run .` –> short build time –> the restore button **still does nothing** in fullscreen
- `cd ../.. && go clean . && go clean -cache`
- `cd examples/window-api`
- `go run .` –> long build time –> the restore button now **works** in fullscreen

Looks like the go build system is failing to detect the changes 🤔

**Comment by leaanthony** [comment]
> Looks like the go build system is failing to pick up the changes 🤔

Oh that suuuucks!

**Comment by leaanthony** [comment]
Yup! That worked great. Thank you!! 🙏

**Pull request merged**
