### PR TITLE
[linux] fix closing of custom context menu #3329

### LINKED ISSUE #3329: [v3 linux] custom context menu closing  immediately
### Description

The context menu opens as soon as the mouse button is pressed and is closed when the mouse button is released.

### To Reproduce

Run `examples/contextmenus` and right click in area `1` or `2`

### Expected behaviour

The context menu should stay open

### Screenshots

https://github.com/wailsapp/wails/assets/8122139/6ff67e7d-6592-4f2b-bf85-a15a522a1545

### Attempted Fixes

_No response_

### System Details

```shell
# Build Environment
Wails CLI    | v3.0.0-alpha.3                          
Go Version   | go1.22.0                                
Revision     | 33946a7aace91ffb1a3992dcf3af7a2071ac70d2
Modified     | true                                    
-buildmode   | exe                                     
-compiler    | gc                                      
CGO_CFLAGS   |                                         
CGO_CPPFLAGS |                                         
CGO_CXXFLAGS |                                         
CGO_ENABLED  | 1                                       
CGO_LDFLAGS  |                                         
GOAMD64      | v1                                      
GOARCH       | amd64                                   
GOOS         | linux                                   
vcs          | git                                     
vcs.modified | true                                    
vcs.revision | 33946a7aace91ffb1a3992dcf3af7a2071ac70d2
vcs.time     | 2024-03-19T10:56:54Z                    

# System
Name         | Manjaro Linux                                                                                                 
Version      | Unknown                                                                                                       
ID           | manjaro                                                                                                       
Branding     |                                                                                                               
Platform     | linux                                                                                                         
Architecture | amd64                                                                                                         
gcc          | 13.2.1-5                                                                                                      
libgtk-3     | 1:3.24.41-1                                                                                                   
libwebkit    | 2.42.5-2                                                                                                      
npm          | 10.5.0-1                                                                                                      
pkg-config   | 2.1.0-2                                                                                                       
CPU          | AMD Ryzen 5 3600 6-Core Processor                                                                             
GPU 1        | Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] (Advanced Micro Devices, Inc. [AMD/ATI]) - Driver: amdgpu 
Memory       | 32GB
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by abichinger**
# Description

- Add `linuxWebviewWindow.ctxMenuOpened` to track if a custom context menu was opened
- connect the `button-release-event` signal to the menu 

Fixes #3329

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
  
Running `examples/contextmenus`

- [ ] Windows
- [ ] macOS
- [x] Linux
  
## Test Configuration

```shell
# Build Environment
Wails CLI    | v3.0.0-alpha.3                          
Go Version   | go1.22.0                                
Revision     | 33946a7aace91ffb1a3992dcf3af7a2071ac70d2
Modified     | true                                    
-buildmode   | exe                                     
-compiler    | gc                                      
CGO_CFLAGS   |                                         
CGO_CPPFLAGS |                                         
CGO_CXXFLAGS |                                         
CGO_ENABLED  | 1                                       
CGO_LDFLAGS  |                                         
GOAMD64      | v1                                      
GOARCH       | amd64                                   
GOOS         | linux                                   
vcs          | git                                     
vcs.modified | true                                    
vcs.revision | 33946a7aace91ffb1a3992dcf3af7a2071ac70d2
vcs.time     | 2024-03-19T10:56:54Z                    

# System
Name         | Manjaro Linux                                                                                                 
Version      | Unknown                                                                                                       
ID           | manjaro                                                                                                       
Branding     |                                                                                                               
Platform     | linux                                                                                                         
Architecture | amd64                                                                                                         
gcc          | 13.2.1-5                                                                                                      
libgtk-3     | 1:3.24.41-1                                                                                                   
libwebkit    | 2.42.5-2                                                                                                      
npm          | 10.5.0-1                                                                                                      
pkg-config   | 2.1.0-2                                                                                                       
CPU          | AMD Ryzen 5 3600 6-Core Processor                                                                             
GPU 1        | Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] (Advanced Micro Devices, Inc. [AMD/ATI]) - Driver: amdgpu 
Memory       | 32GB                                                                                                          

# Diagnosis
 SUCCESS  Your system is ready for Wails development!
```

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by tmclane — APPROVED** [review]
Looks good but I can't validate it on Manjaro.

**Comment by atterpac** [comment]
Tested and confirmed working in the following environment (Ubuntu 22.02)
```
# Build Environment
Wails CLI    | v3.0.0-alpha.3
Go Version   | go1.21.4
-buildmode   | exe
-compiler    | gc
CGO_CFLAGS   |
CGO_CPPFLAGS |
CGO_CXXFLAGS |
CGO_ENABLED  | 1
CGO_LDFLAGS  |
GOAMD64      | v1
GOARCH       | amd64
GOOS         | linux

# System
Name         | Ubuntu
Version      | 22.04
ID           | ubuntu
Branding     | 22.04.3 LTS (Jammy Jellyfish)
Platform     | linux
Architecture | amd64
gcc          | 12.9ubuntu3
libgtk-3     | 3.24.33-1ubuntu2
libwebkit    | 2.42.5-0ubuntu0.22.04.2
npm          | 8.5.1~ds-1
pkg-config   | 0.29.2-1ubuntu3
CPU          | 12th Gen Intel(R) Core(TM) i5-1235U
GPU 1        | unknown (Intel Corporation) - Driver: i915
Memory       | 7GB
```

**Comment by leaanthony** [comment]
Thanks 🙏 Please could you add an entry to the changelog located at `mkdocs-website/docs/changelog.md`? Thanks!

**Comment by abichinger** [comment]
Done :)

**Review by leaanthony — APPROVED** [review]
Thanks for doing this.

**Pull request merged**
