### PR TITLE
[v3/windows] Add an implementation of the `SetIcon` method

### PR DESCRIPTION
**Pull request by almas1992**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Before:
image

After:
image

## Type of change
  
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [x] Windows
- [ ] macOS
- [ ] Linux
  
## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [ ] My code follows the general coding style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by almas1992** [comment]
Woops! This change breaks the functionality of the `DisableIcon` option.

**Comment by leaanthony** [comment]
You should be able to get the options from the `globalApplication` and check this value

**Comment by almas1992** [comment]
> You should be able to get the application using `application.Get()` and check this value in the options before continuing

`DisableIcon` is a `application.WebviewWindow` option, not an `application.Option`, and it's in every window, independent of each other.

**Comment by leaanthony** [comment]
That'll teach me to answer on mobile 😂 Even easier!

**Comment by leaanthony** [comment]
I'm assuming this is for runtime updates? Both icons indicated in the picture work fine in build

**Comment by almas1992** [comment]
> I'm assuming this is for runtime updates? Both icons indicated in the picture work fine in build

Yes, this is updating icons at runtime.The screenshot shows the direct run `go run main.go`😂

**Comment by almas1992** [comment]
If I'm not mistaken, `setIcon` is also called when the app is launched. https://github.com/wailsapp/wails/blob/cf7537df018189d4ad75dffc918baacdd141ed50/v3/pkg/application/application.go#L493

**Comment by leaanthony** [comment]
@almas1992 - Did you find a resolution for when you disable the icon?

**Comment by almas1992** [comment]
> @almas1992 - Did you find a resolution for when you disable the icon?

No, I haven't found an effective solution yet. 🫠

**Pull request closed without merging**
