### PR TITLE
Add EnableFraudulentWebsiteDetection to options

### LINKED ISSUE #2163: Disable SmartScreen / FraudulentWebsite detection
### Is your feature request related to a problem? Please describe.

Microsoft uses SmartScreen per default in WebView2 to detect if a user is accessing a phishing or malware website. The same applies to Apple, they use a "FraudulentWebsite" detection service.

Both services send information about the navigation to Microsoft/Apple. It's not clear if this only applies to External Websites or also to custom protocols or what is included.

### Describe the solution you'd like

It would be great to have the possibility to disable this detection. Maybe even better per default disable it and the developer needs to opt-in.

How to disable it:
- Apple [fraudulentWebsiteWarningEnabled](https://developer.apple.com/documentation/webkit/wkpreferences/3335219-fraudulentwebsitewarningenabled?language=objc)  
- Microsoft: https://github.com/MicrosoftEdge/WebView2Feedback/issues/834

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by stffabi**
This allows to explicitly opt-in to scan services for fraudulent
content, such as malware or phishing attempts.

Fixes #2163

### CODE REVIEW

**Comment by stffabi** [comment]
@leaanthony do you think it should be opt-in or opt-out? I tend it to be opt-in but that will change the behaviour of existing apps.

**Review by leaanthony — APPROVED** [review]
LGTM

**Comment by leaanthony** [comment]
> @leaanthony do you think it should be opt-in or opt-out? I tend it to be opt-in but that will change the behaviour of existing apps.

I think it should be opt-in for v2 so that it doesn't change behaviour and opt-out for v3.

**Comment by stffabi** [comment]
I've updated the PR to invert the logic. @leaanthony would you mind taking another look?

**Comment by leaanthony** [comment]
I had a think about this overnight.... I don't recall anyone reporting this warning so maybe disabling by default is actually fine?

**Comment by stffabi** [comment]
Reverted back to the original version.

**Comment by leaanthony** [comment]
Nice one! Thanks for doing that 🙏

**Pull request merged**
