### PR TITLE
feat(website): sync documents and add content

### PR DESCRIPTION
**Pull request by misitebao**
- Add a directory to the website
- Update site navigation menu
- Update site tagline(Emphasis on cross-platform)
- Sync the changelog of the latest version to the website

### CODE REVIEW

**Comment by misitebao** [comment]
@leaanthony 
Do you see if there is anything that needs to be modified or added?

**Comment by leaanthony** [comment]
This is great - thanks. I'm wondering if we need appendix right now? Maybe add it when we have content? What do you think?

**Comment by misitebao** [comment]
@leaanthony 
The `appendix` directory has been temporarily removed, it will not show up in the documentation.

**Comment by leaanthony** [comment]
LGTM

**Pull request merged**
