### PR TITLE
Update built-in Svelte JS and TS templates

### PR DESCRIPTION
**Pull request by KiddoV**
# Description

Update Svelte to latest version 4.2.0 and also its dependencies.

Also added a default ``favicon`` base64 image to prevent ``missing favicon`` error in ``index.html`` file.

Fixes # (issue)
https://github.com/wailsapp/wails/issues/2888

# How Has This Been Tested?
``wails init``

- [x] Windows
- [ ] macOS
- [ ] Linux
  
## Test Configuration
          Wails Doctor

Wails
Version | v2.6.0

System
┌────────────────────────────────────────────────┐
| OS           | Windows 10 Enterprise LTSC 2021 |
| Version      | 2009 (Build: 19044)             |
| ID           | 21H2                            |
| Go Version   | go1.19                          |
| Platform     | windows                         |
| Architecture | amd64                           |
└────────────────────────────────────────────────┘

Dependencies
┌───────────────────────────────────────────────────────┐
| Dependency | Package Name | Status    | Version       |
| WebView2   | N/A          | Installed | 116.0.1938.76 |
| Nodejs     | N/A          | Installed | 16.17.0       |
| npm        | N/A          | Installed | 8.15.0        |
| *upx       | N/A          | Installed | upx 3.96      |
| *nsis      | N/A          | Available |               |
└─────────────── * - Optional Dependency ───────────────┘

Diagnosis
Optional package(s) installation details:
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by leaanthony** [comment]
@KiddoV - Was this generated from Vite? We generally update the templates all in one go using Vite's template generation.

**Comment by KiddoV** [comment]
This is update manually, I am not sure how Vite can auto generate new version for Svelte.

**Comment by KiddoV** [comment]
@leaanthony Svelte is growing too fast, not sure if we should wait for Svelte 5 first? LOL
https://svelte.dev/blog/runes

**Comment by leaanthony** [comment]
@KiddoV - I appreciate the time you put into this 🙏 I think we should stick to the current system of keeping the templates in sync with Vite. However, if you want to host this template, I think that could benefit some people. Thoughts?

**Comment by KiddoV** [comment]
@leaanthony I agreed, let keep it that way... for now!

**Pull request closed without merging**
