### PR TITLE
[v3] export `SetIcon` method

### PR DESCRIPTION
**Pull request by almas1992**
# Description

Export `SetIcon` method.

## Type of change
  
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [ ] Windows
- [x] macOS
- [ ] Linux
  
## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [ ] My code follows the general coding style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by leaanthony** [comment]
Are you sure this is going to work on each platform at runtime?

**Comment by almas1992** [comment]
> Are you sure this is going to work on each platform at runtime?

Only work on Mac , because  `setIcon` method is not implemented on [Linux](https://github.com/wailsapp/wails/blob/51afac4f221427cd298bb7c91414a147335f8147/v3/pkg/application/application_linux.go#L61) and [Windows](https://github.com/wailsapp/wails/blob/51afac4f221427cd298bb7c91414a147335f8147/v3/pkg/application/application_windows.go#L155)

**Comment by almas1992** [comment]
And it is possible to set icon at runtime on Windows, There is electron package https://github.com/NexovaDev/electron-taskbar-badge

**Comment by leaanthony** [comment]
Badge and icon are different. I'm ok with this going in though.

**Comment by almas1992** [comment]
> Badge and icon are different. I'm ok with this going in though.

I know that is different. But the election package set badge via overlay task bare icon.

**Pull request merged**
