### PR TITLE
Added possibility to specify platform for dev command

### PR DESCRIPTION
**Pull request by evsign**
# Description

During development under Wsl, there is currently no way to use the `wails dev` command to build a Windows executable and I thought that it would be nice and convenient to have such. These changes allow specifying the platform for the `wails dev` command. Example: `wails dev --platform=windows`.

Currently, there is no open issue for this feature. If it needs to be created, please let me know, and I'll create it.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by leaanthony** [comment]
Hi! Thanks for taking the time to open this. Could you please open a ticket and detail the scenarios in which this might be used? I'm not familiar with wsl or what this use case looks like. Thanks! 🙏

**Comment by krdkuzya** [comment]
Привет, это Tisso, ты куда пропал) Отпиши в тг Krdgoblin

**Comment by krdkuzya** [comment]
Привет, это Tisso, ты куда пропал) Отпиши в тг Krdgoblin

**Comment by leaanthony** [comment]
> Hi, this is Tisso, where have you gone) Write to tg Krdgoblin

Please stop.

**Comment by PylotLight** [comment]
@leaanthony This would actually be super useful. Currently wails dev run through WSL loads a Linux app which looks poor is annoying to interact with and doesn't work in some cases where Linux GUI apps are not supported in WSL. If we could instead direct dev to launch a windows app, that would be way better.

image

**Comment by leaanthony** [comment]
What's the advantage of Dev in WSL vs just plain windows? Windows is by far the better supported platform.

**Comment by PylotLight** [comment]
It's widely accepted that working and coding in Linux is a far superior platform and experience for a variety of reasons. For those of us who need or want Linux but still need some of the features of windows for daily use then WSL allows us to have the best of both worlds. This would be a very long comment if you want me to explain why WSL is useful or beneficial, but myself and many others, have been using it for years.

**Comment by leaanthony** [comment]
Thanks 🙏 Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

**Comment by PylotLight** [comment]
@evsign Can you finish this one off plz. 🙏

**Comment by PylotLight** [comment]
@leaanthony Would need a rebase by now. Perhaps we either just copy the changes into a new PR and close this one. Or just close as this is in v3 already anyway?

**Comment by leaanthony** [comment]
If you want to take over this PR we could look at it?

**Comment by PylotLight** [comment]
@leaanthony Sure. Just need to update feature/dev-platform correct?
I updated my local wails repo cause I forgot I don't have access to push from that, so just need to do the same thing from my fork I think, not sure how that connects into this PR tho.

**Comment by PylotLight** [comment]
Created working copy: https://github.com/wailsapp/wails/pull/3117

**Comment by leaanthony** [comment]
Closing in favour of: https://github.com/wailsapp/wails/pull/3117

**Pull request closed without merging**
