### PR TITLE
chore(action): add auto sync script

### PR DESCRIPTION
**Pull request by misitebao**
Added site auto-sync script(8:00 and 20:00 every day) to keep mirror sites in sync with the official site at all times.

### CODE REVIEW

**Comment by leaanthony** [comment]
Happy to do auto-sync but please explain what this is doing. Looks like we need to add secrets?

**Comment by misitebao** [comment]
@leaanthony 
This is to automatically synchronize the `wailsapp/wails` warehouse to `misitebao/wails`, and rebuild and deploy the mirror website (wails.top). It only works in the `misitebao/wails` warehouse, and you don't need to do anything.

**Comment by leaanthony** [comment]
I'm trying to understand why we need the upstream branch. Why not sync from master?

**Comment by misitebao** [comment]
@leaanthony 
It is the upstream repository, not the upstream branch, because the mirror website construction and deployment must be done in the `misitebao/wails repository. It is impossible for me to manually maintain synchronization with the wailsapp/wails repository, so I can only use scheduled tasks to achieve it.

**Pull request merged**
