### PR TITLE
Chore/react 18 create root

### PR DESCRIPTION
**Pull request by tomanagle**
- Updates the react & react-ts frontends to use `createRoot` instead of `ReactDOM.render` as ReactDOM.render is no longer supported in React 18 

Docs: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

### CODE REVIEW

**Review by sidwebworks — APPROVED** [review]
Looks good :smile:

**Comment by leaanthony** [comment]
Thanks for doing this! Is there any chance you could add them to the directories under `generate`? My fear is they'll get overwritten next time we generate the templates again. It should be fairly obvious what's happening in the generate directory (those files are copied after a default vite generation) but if you need more info, I'm happy to help! 🙏

**Comment by tomanagle** [comment]
> Thanks for doing this! Is there any chance you could add them to the directories under `generate`? My fear is they'll get overwritten next time we generate the templates again. It should be fairly obvious what's happening in the generate directory (those files are copied after a default vite generation) but if you need more info, I'm happy to help! 🙏

Yup, I'll take a look around and update the PR :)

**Comment by tomanagle** [comment]
I updated those templates (hopefully in the right place).

Also realised my linter was changing more lines than required, so fixed that up too

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
Thanks for this!

**Pull request merged**
