### PR TITLE
Added wails-qwik-template to 3rd party templates

### PR DESCRIPTION
**Pull request by LazyClicks**
# Description

Wails template that uses qwik for the frontend

Fixes # (issue)

## Type of change
  
Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [x] Windows : initialized a new wails project using the template and ran wails build and wails dev
  
## Test Configuration

DEB | Using go webview2loader
Wails CLI v2.5.1

 SUCCESS  Done.

# System

OS           | Windows 10 Pro
Version      | 2009 (Build: 22621)
ID           | 22H2
Go Version   | go1.21.0
Platform     | windows
Architecture | amd64

# Wails

Version | v2.5.1

# Dependencies

Dependency | Package Name | Status    | Version
WebView2   | N/A          | Installed | 115.0.1901.203
Nodejs     | N/A          | Installed | 18.16.1
npm        | N/A          | Installed | 9.5.1
*upx       | N/A          | Available |
*nsis      | N/A          | Available |
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
Optional package(s) installation details:
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

# Checklist:

- [x] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [x] My code follows the general coding style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by leaanthony — COMMENTED** [review]
Is the link text correct?

**Review by leaanthony — COMMENTED** [review]
fix typo

**Comment by leaanthony** [comment]
Thanks @LazyClicks !

**Comment by LazyClicks** [comment]
mb i didn't notice that mistake and was at work the whole day, thank you for correcting it

**Pull request merged**
