### PR TITLE
#3200: Use OutputFilename instead of Name

### PR DESCRIPTION
**Pull request by plutov**
Issue: https://github.com/wailsapp/wails/issues/3200

Solution: use `options.ProjectData.OutputFilename` instead of `options.ProjectData.Name`

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved error messaging in the MacOS build process to reference "CompiledBinary" instead of "OutputFilename".
  - Fixed the MacOS build process to correctly utilize `outputfilename` from `wails.json`.

- **Documentation**
  - Updated the changelog with the latest fix for the MacOS build process.

### CODE REVIEW

**Comment by leaanthony** [comment]
Thanks 🙏 Please could you add an entry to the changelog located at `website/src/pages/changelog.mdx`?

**Review by leaanthony — APPROVED** [review]

**Comment by leaanthony** [comment]
What happens if you set your output filename in the Json to a blank string?

**Comment by plutov** [comment]
Good question @leaanthony I noticed that we set it to name by default:
```
if p.OutputFilename == "" {
  p.OutputFilename = p.Name
}
```

**Comment by leaanthony** [comment]
LGTM. If you could just update the change log we'll look to get this in

**Comment by plutov** [comment]
@leaanthony done, I put it under `Unreleased`, not sure if it's the right place.

**Comment by leaanthony** [comment]
I suspect this might be a breaking change for some people 🤔

**Comment by leaanthony** [comment]
Thanks for your patience! I'll merge this and highlight the change in the release notes 👍

**Pull request merged**
