### PR TITLE
Appargs

### PR DESCRIPTION
**Pull request by phoenix147**
I added appargs for providing application arguments in dev mode. They are parsed with github.com/google/shlex in shell style and forwarded to the application binary.
I also adapted the documentation accordingly.

I've tested it without appargs, appargs via CLI and also appargs using the project config.

### CODE REVIEW

**Comment by leaanthony** [comment]
This is great. Thanks for also updating the docs. LGTM!

**Comment by leaanthony** [comment]
I tried generating a new project using master and it is broken. The only thing I can think of is this PR. Does it work for you?

**Comment by phoenix147** [comment]
I just tried with my branch and it's working.
What error do you get?

```
 Z:\wails\v2\wails.exe init -n "name"
Wails CLI v2.0.0-beta.15


Initialising Project Name
-------------------------

go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/leaanthony/go-webview2 v0.0.0-20210914103035-f00aa774a934
go: downloading golang.org/x/sys v0.0.0-20210823070655-63515b42dcdf
go: downloading github.com/jchv/go-winloader v0.0.0-20200815041850-dec1ee9a7fd5
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c

Project Name:      name
Project Directory: C:\Users\User\Documents\temp\name
Project Template:  vanilla
Template Support:  https://github.com/wailsapp/wails

Initialised project 'name' in 28.801s.


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

PS C:\Users\User\Documents\temp> cd .\name\
PS C:\Users\User\Documents\temp\name> Z:\wails\v2\wails.exe build
Wails CLI v2.0.0-beta.15



App Type:               desktop
Platform:               windows
Arch:                   amd64
Compiler:               C:\Program Files\Go\bin\go.exe
Skip Frontend:          false
Compress:               false
Package:                true
Clean Build Dir:        false
LDFlags:                ""
Tags:                   []

No Install command. Skipping.
No Build command. Skipping.
Generating bundle assets: Done.
Compiling application: Done.

Built 'C:\Users\User\Documents\temp\name\build\bin\name.exe' in 7.605s.


If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

```

**Comment by phoenix147** [comment]
@leaanthony 

For me wails dev did not work (file not found), but this was because the go.mod file was pointing to beta.15 and not the current master

**Comment by leaanthony** [comment]
Ah, perfect. My mistake. Thanks for trying 🙏

**Comment by leaanthony** [comment]
@phoenix147 - I just discovered that this PR broke the IDE config generation. I've re-introduced the flags (they are part of the docs too) but it will only attempt to use them if the `assetdir` env var isn't found. Could you check that this doesn't break your app?

**Comment by phoenix147** [comment]
@leaanthony What do you mean with IDE config generation?
I will take a look today in the evening or tommorrow.

**Comment by leaanthony** [comment]
The `-ide` option generates ide config that have dev modes and were configured to use the flags

**Comment by phoenix147** [comment]
@leaanthony everything works as expected with beta.20

**Pull request merged**
