### PR TITLE
go vet cleanup

### PR DESCRIPTION
**Pull request by tmclane**
Updated to remove only one line of `unreachable` code.

### CODE REVIEW

**Comment by tmclane** [comment]
Ah I forgot we weren't supporting older Go versions any longer.
The `goimports` adds it automatically I think for backwards-compatibility.
I can take that out.

**Review by leaanthony — COMMENTED** [review]
That reduced it down to 1 line! Do you know why the return was removed?

**Comment by tmclane** [comment]
Because of the `default` case in the `switch` statement the final line in the function will never fire.

**Comment by tmclane** [comment]
I am thinking that perhaps leaving the final return and updating the `default` case to not do a `return` might be more appropriate.

**Comment by leaanthony** [comment]
It's hard to review on mobile 😅

**Comment by leaanthony** [comment]
I think it's ok as is 👍

**Review by leaanthony — APPROVED** [review]

**Pull request merged**
