### PR TITLE
refactor(website): upgrade site to `docusaurus@2.0.0-beta.17`

### PR DESCRIPTION
**Pull request by misitebao**
Temporarily remove `react-contributors` due to incompatibility

### CODE REVIEW

**Comment by misitebao** [comment]
@leaanthony 
Don't merge for now, I'll re-develop and release a similar component to be compatible with the current project.

**Comment by misitebao** [comment]
@leaanthony 
The upgrade is done and you can test it out.

**Comment by misitebao** [comment]
@leaanthony 
This branch passed the tests but has not been merged, are there any other issues?

**Comment by leaanthony** [comment]
Awesome! Beta.18 is out already 👍

**Pull request merged**
