### PR TITLE
[v2 templates] Add explicit style import

### LINKED ISSUE #2705: [linux, dev] CSS included with "link"-tag do not work
### Description

follow guide
```shell
wails init -n wails-dev -t vue
```
and then run
```shell
wails dev
```
but application shows below
Screenshot from 2023-06-06 16-48-30
as you see,the text not align center,but in  browser ,It's ok
Screenshot from 2023-06-06 16-51-52
and terminal print
Screenshot from 2023-06-06 16-49-00
while I use 
```shell
wails build
```
and then use the binary file ,It's fine,Just dev mode It not work.
What's the matter? My OS is Ubuntu 22.04.2 LTS

### To Reproduce

```shell
wails init -n wails-dev -t vue
```
```shell
wails dev
```

### Expected behaviour

display same as browser

### Screenshots

_No response_

### Attempted Fixes

_No response_

### System Details

```shell
Wails CLI v2.5.1

 SUCCESS  Done.                                                                                                                                                                                                    

# System

OS           | Ubuntu  
Version      | 22.04   
ID           | ubuntu  
Go Version   | go1.18.3
Platform     | linux   
Architecture | amd64   

# Wails

Version         | v2.5.1
Package Manager | apt   

# Dependencies

Dependency | Package Name          | Status    | Version                
*docker    | docker.io             | Installed | 24.0.2                 
gcc        | build-essential       | Installed | 12.9ubuntu3            
libgtk-3   | libgtk-3-dev          | Installed | 3.24.33-1ubuntu2       
libwebkit  | libwebkit2gtk-4.0-dev | Installed | 2.38.6-0ubuntu0.22.04.1
npm        | npm                   | Installed | 8.19.4                 
*nsis      | nsis                  | Installed | v3.08-2                
pkg-config | pkg-config            | Installed | 0.29.2                 
* - Optional Dependency

# Diagnosis

Your system is ready for Wails development!
 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leaanthony**
# Description

Templates have been updated to include an explicit import for `style.css`.

Fixes #2705

### CODE REVIEW

**Comment by stffabi** [comment]
LGTM.

Maybe we should also remove the old ```<link href="./src/style.css" rel="stylesheet">``` for those templates?

**Comment by stffabi** [comment]
@leaanthony can we merge this? I think we should also remove the normal link hrefs.

**Comment by leaanthony** [comment]
Sorry - slipped the net. Approve and it'll merge 👍

**Review by stffabi — APPROVED** [review]
LGTM, thanks 👍

**Pull request merged**
