### PR TITLE
Change the default port for frontend vite startup

### PR DESCRIPTION
**Pull request by Soonogo**
# Description

Initialize the frontend vite template using the default port 5173 so that it changes to 9245

## Type of change
  
Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
  
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration using `wails doctor`.

- [ ] Windows
- [x] macOS
- [ ] Linux
  
# System
| Name          | MacOS        |
|-------|-----------|
| Version       | 14.1.2       |
| ID            | 23B92        |
| Branding      | Sonoma       |
| Platform      | darwin       |
| Architecture  | arm64        |
| Apple Silicon | true         |
| CPU           | Apple M1 Pro |
| CPU           | Unknown      |
| GPU           | Unknown      |
| Memory        | Unknown      |

# Build Environment

| Wails CLI    | v3.0.0-alpha.6 |
|-------|-----------|
| Go Version   | go1.22.5       |
| -buildmode   | exe            |
| -compiler    | gc             |
| CGO_CFLAGS   |                |
| CGO_CPPFLAGS |                |
| CGO_CXXFLAGS |                |
| CGO_ENABLED  | 1              |
| CGO_LDFLAGS  |                |
| GOARCH       | arm64          |
| GOOS         | darwin         |

## Test Configuration

Please paste the output of `wails doctor`. If you are unable to run this command, please describe your environment in as much detail as possible.

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [ ] My code follows the general coding style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Introduced a configurable server port (9245) for the Vite development server across various frontend frameworks (Preact, Qwik, React, Solid, Svelte, Vue).
	- This enhancement allows developers to avoid port conflicts and customize their local development environments more effectively.

These changes improve the flexibility and configurability of the development setup for users.

### CODE REVIEW

**Comment by leaanthony** [comment]
why?

**Comment by Soonogo** [comment]
> why?

https://github.com/wailsapp/wails/blob/v3-alpha/v3/internal/commands/dev.go#L12
I saw it written here that the boot port is 9245.

**Comment by atterpac** [comment]
We had set this in the taskfile but i don't hate moving it to the typescript config file but we should remove it from the [dev task](https://github.com/wailsapp/wails/blob/4591fb9b956e315f59d7ec96d9a7130fc9423309/v3/internal/templates/_common/Taskfile.tmpl.yml#L33) if using the config file instead.

**Comment by leaanthony** [comment]
I'm going to close this because there's a chance someone will change it in the config and this won't be reflected in the taskfile (where it's needed) and cause confusion. Thanks for raising this PR though!

**Pull request closed without merging**
