### PR TITLE
Linux db

### PR DESCRIPTION
**Pull request by leaanthony**

### CODE REVIEW

**Comment by leaanthony** [comment]
@bh90210 Let me know what you think of this :-)

**Comment by bh90210** [comment]
checking it asap

**Comment by bh90210** [comment]
please give me a sec though, cause I get `Error: Program 'npm' not found.` from debian and I am not sure if it is something wrong with my Dockerfile..

**Comment by bh90210** [comment]
OK it turns out debian9's default node version is `nodejs is already the newest version (4.8.2~dfsg-1).`
so the proper way to install the latest is via 
`curl -sL https://deb.nodesource.com/setup_12.x | sudo bash - && sudo apt-get install -y nodejs`

maybe debian and ubuntu should be different, since many sub-distros go for one or the other.
in any way the above `linuxdb.yaml` will work for every supported distribution :+1:

**Comment by leaanthony** [comment]
So currently Debian inherits from Ubuntu so already has curl -sL `https://deb.nodesource.com/setup_12.x | sudo bash - && sudo apt-get install -y nodejs`. Did I need to update something?

**Pull request merged**
