### PR TITLE
Fix multiple nested `build/bin` folders in `dev` mode

### PR DESCRIPTION
**Pull request by OlegGulevskyy**
Following discussion in #2100 - this PR removes assignment to path where executable is stored (`/build/bin`). This was adding `/build/bin` to the executable name on each save in `dev` mode, which results in `/build/bin/build/bin...` duplicated nested path.

Have tested on MacOS only, can test on Windows 11 a bit later to make sure no regression

### CODE REVIEW

**Review by leaanthony — APPROVED** [review]

**Comment by stffabi** [comment]
LGTM, would it be possible for you to also add your changes to the changelog here `website/src/pages/changelog.mdx`? That would be awesome 🙏

**Comment by OlegGulevskyy** [comment]
Of course, done!
Will keep in mind `changelogs` from now on :)

**Comment by leaanthony** [comment]
Yeah, that's how we're tracking changes because GitHub's commit message bundle isn't good enough 😀

**Comment by leaanthony** [comment]
I tested on Windows 11:
* Generate new project
* `wails dev`, then close
* `wails dev`, then close
* Checked FS, all good
* `wails build` - all good 

Thanks heaps @OlegGulevskyy 🙏

**Pull request merged**
