### PR TITLE
Azure Pipelines

### PR DESCRIPTION
**Pull request by bh90210**

### CODE REVIEW

**Comment by bh90210** [comment]
I was actually expecting azure to pick up the `yaml`
what happened?

**Comment by bh90210** [comment]
this is the windows error I get from azure when I run it on my own account (linux, max are ok)
```
##[section]Starting: Check we have output
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
wails version
========================== Starting Command Output ===========================
##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "d:\a\_temp\0e6b3194-3a24-4a45-b3e7-30076d2266a4.cmd""
'wails' is not recognized as an internal or external command,
operable program or batch file.
##[error]Cmd.exe exited with code '1'.
##[section]Finishing: Check we have output

```

**Comment by bh90210** [comment]
https://github.com/bh90210/wails/pull/24

**Comment by leaanthony** [comment]
> this is the windows error I get from azure when I run it on my own account (linux, mac are ok)
> 
> ```
> ========================== Starting Command Output ===========================
> ##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "d:\a\_temp\0e6b3194-3a24-4a45-b3e7-30076d2266a4.cmd""
> 'wails' is not recognized as an internal or external command,
> operable program or batch file.
> ##[error]Cmd.exe exited with code '1'.
> ##[section]Finishing: Check we have output
> ```

I think this is because %PATH% doesn't have the go bin path. It may need something like `set PATH=%PATH%;D:\go\bin`

**Comment by bh90210** [comment]
yeap *it is because of this* I just couldn't figure out how to do it in windows terminal, trying right now what u suggested thu :+1:

**Comment by bh90210** [comment]
I hate windows now :laughing: but got it working :+1: 
please check https://github.com/bh90210/wails/pull/24
win

**Comment by bh90210** [comment]
also consider closing #142

**Comment by leaanthony** [comment]
OMG. This is insane effort! This gives us a fantastic platform to build on and help us with auto testing. 👍 👍 🏅 🎖

**Pull request merged**
