### PR TITLE
[v3 alpha test] `X` and `Y` in WebviewWindowOptions do nothing

### PR DESCRIPTION
**Pull request by takuyahara**
# Description

In `v3/pkg/application/webview_window_darwin.go` there's no logic that involves `options.X` and `options.Y` and window is [always](https://github.com/wailsapp/wails/blob/308304b75e4e83b5aea33087e17641ac84b3bda8/v3/pkg/application/webview_window_darwin.go#L1232) centered, so `X` and `Y` in WebviewWindowOptions do nothing.

```go
app.NewWebviewWindowWithOptions(application.WebviewWindowOptions{
    Title: "Window 1",
    URL:   "/",
    // It works as if they are not set and window is always centered
    X:     320,
    Y:     240,
})
```

This PR fixes `X` `Y` issue and requires to set `Centered: true` exclusively to launch window centered. When both `X` `Y` and `Centered: true` are set the latter one is prioritized.

```go
app.NewWebviewWindowWithOptions(application.WebviewWindowOptions{
    Title:    "Window 1",
    URL:      "/",
    // X:        320, // overrode by `Centered: true`
    // Y:        240, // overrode by `Centered: true`
    Centered: true,
})
```

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
  
- [ ] Windows
- [x] macOS
- [ ] Linux
  
## Test Configuration

```
# Wails
Version | v2.9.2

# System
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
| OS           | MacOS                                                                                                                  |
| Version      | 15.0.1                                                                                                                 |
| ID           | 24A348                                                                                                                 |
| Go Version   | go1.22.7                                                                                                               |
| Platform     | darwin                                                                                                                 |
| Architecture | arm64                                                                                                                  |
| CPU          | Apple M2                                                                                                               |
| GPU          | Chipset Model: Apple M2 Type: GPU Bus: Built-In Total Number of Cores: 8 Vendor: Apple (0x106b) Metal Support: Metal 3 |
| Memory       | 16GB                                                                                                                   |
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

# Dependencies
┌───────────────────────────────────────────────────────────────────────┐
| Dependency                | Package Name | Status    | Version        |
| Xcode command line tools  | N/A          | Installed | 2349           |
| Nodejs                    | N/A          | Installed | 22.8.0         |
| npm                       | N/A          | Installed | 10.8.2         |
| *Xcode                    | N/A          | Installed | 9.4.1 (17E189) |
| *upx                      | N/A          | Available |                |
| *nsis                     | N/A          | Available |                |
└─────────────────────── * - Optional Dependency ───────────────────────┘

# Diagnosis
Optional package(s) installation details: 
  - upx : Available at https://upx.github.io/
  - nsis : More info at https://wails.io/docs/guides/windows-installer/

 SUCCESS  Your system is ready for Wails development!

 ♥   If Wails is useful to you or your company, please consider sponsoring the project:
https://github.com/sponsors/leaanthony

```

# Checklist:

- [ ] I have updated `website/src/pages/changelog.mdx` with details of this PR
- [ ] My code follows the general coding style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Summary by CodeRabbit

- **New Features**
	- Added a `Centered` option to the webview window configuration, ensuring that windows open centered on the screen across various examples.
	- Introduced periodic event emission in the `events` example, enhancing interactivity.
- **Bug Fixes**
	- Adjusted formatting for consistency in window options across multiple examples. 
- **Documentation**
	- Improved clarity on window centering behavior in the user interface.

### CODE REVIEW

**Comment by leaanthony** [comment]
Hi there! Thanks for this PR.

Adding an explicit center config is ok, but I'm wondering what would happen if this was false and X/Y wasn't specified. Would that move the window to 0,0 on the screen? This feels like the default behaviour but I think most people would think that centering should be the default.

Thoughts?

Please also open a post in the discord channel where all v3 discussion is taking place, as mentioned here: https://v3alpha.wails.io/getting-started/feedback/

**Comment by takuyahara** [comment]
> but I'm wondering what would happen if this was false and X/Y wasn't specified. Would that move the window to 0,0 on the screen? 

Yes.

> This feels like the default behaviour but I think most people would think that centering should be the default.

When X/Y wasn't specified it's equivalent to 0 has passed for both, so you have to override (0, 0) to centering window but it kills a freedom of moving it to (0, 0). I propose to preserve a freedom of moving window to everywhere and centering window to be explicit.

> Please also open a post in the discord channel where all v3 discussion is taking place, as mentioned here:

Already did here.
https://discord.com/channels/1042734330029547630/1299131890149888041/1299131890149888041

**Comment by leaanthony** [comment]
Thanks for the clarification. We'll update the PR templates to indicate that we'd expect a discussion around the feature before opening a PR so we have all of that in one place. Moving this conversation there for more feedback 👍

**Comment by leaanthony** [comment]
Closing in favour of #3885. Thanks so much for brining this up!

**Pull request closed without merging**
