### PR TITLE
feat: VoidLinux support

### PR DESCRIPTION
**Pull request by Vaelatern**

### CODE REVIEW

**Comment by leaanthony** [comment]
Hi! Any chance you could change the PR so it is against the `develop` branch? Thanks :-)

**Comment by Vaelatern** [comment]
Ah. Seems I need to make some changes.

**Comment by leaanthony** [comment]
Thanks @Vaelatern. `develop` is our main branch, `master` is only used for stable releases.

**Comment by Vaelatern** [comment]
Changes made.

**Comment by Vaelatern** [comment]
Given guidance about what is expected from the cmd/linuxdb.yaml file, I can patch that too. It's a bit of a departure from the system I already learned for the initial PR.

**Comment by bh90210** [comment]
hey @Vaelatern 
yes as much guidance as you wnat :smiley: 

basically use for example centos entry, as a boilerplate and replace libraries names etc

I am also working on producing a container to check your PR.

**Comment by Vaelatern** [comment]
How's this?

**Comment by bh90210** [comment]
yes yes I found everything on BUT thanks a lot! 
Just woke up so please give me a few hours before giving a proper review :smiley:

**Comment by leaanthony** [comment]
This looks good to me but will wait for @bh90210 to confirm 👍

**Comment by leaanthony** [comment]
If there are void containers, we can look at getting it into the testing pipeline 🚀

**Comment by bh90210** [comment]
@Vaelatern actually yes I'd love some help with the Dockerfile! lmao
I gave it a try, can make it work, seems time waster, if you could help make it faster that'd be amazing.

here I am collecting all Dockerfiles for linux testing.
the tooling we need in the container `git curl wget base-devel pkg-config nodejs gtk+3-devel webkit2gtk-devel`
here is an example Dockerfile for ubuntu
```dockerfile
FROM ubuntu:18.04
LABEL wails="removeall" maintainer="ktc@protonmail.com"

RUN apt-get update && \
 apt-get install -y git curl wget libgtk-3-dev libwebkit2gtk-4.0-dev build-essential npm nodejs && \
 wget https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz && tar -C /usr/local -xzf go1.12.7.linux-amd64.tar.gz && \
 rm -rf /var/lib/apt/lists/*
```

https://github.com/bh90210/wails-linux-scirpts/blob/master/supported-distros/voidlinux-musl/Dockerfile here is my approach thus far with voidlinux but I get this error
```bash
docker run --rm -it -t wails-voidlinux-musl
docker: Error response from daemon: No command specified.
See 'docker run --help'.
```
and
```
docker run --rm -it -t wails-voidlinux-musl /bin/bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.
```

**Comment by Vaelatern** [comment]
Can I ask why your dockerfiles all refuse to use the packaged version of golang?

**Comment by Vaelatern** [comment]
The following works great for me.

```
FROM voidlinux/voidlinux-musl:latest
LABEL wails="removeall" maintainer="ktc@protonmail.com"

RUN xbps-install -Syu
RUN xbps-install -Syu
RUN xbps-install -Sy go git curl wget base-devel pkg-config nodejs gtk+3-devel webkit2gtk-devel
CMD bash
```
Remember that go-bin from upstream google may not work, especially for musl, because the upstream bins are linked against glibc.

Just trust that the Void Linux team will keep golang updated, please.

**Comment by bh90210** [comment]
good-morning. again, just woke up, gimme a few hours to get this PR going..

yes I did a quick research on void-musl and came across glibc vs libc.
I mostly chose to do it this way cause when I find time to upgrade the tester cli, I will enable it to actually choose go version as well.

**Comment by Vaelatern** [comment]
I don't understand why I still can't init a new wails project due to distro not being in the found list.

**Comment by bh90210** [comment]
I'm afraid I still can not start the container
I copy-pasted your Dockerfile from above and I still get 
```bash
docker run --rm -it -t wails-test-voidlinux-musl
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.
```

**Comment by Vaelatern** [comment]
Well, bash is present on every Void system. I can't duplicate exactly your command because I get:
```
Unable to find image 'wails-voidlinux-musl:latest' locally
docker: Error response from daemon: pull access denied for wails-voidlinux-musl, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
But `docker build` works.

**Comment by bh90210** [comment]
@leaanthony got it testing and has the same problem with elementary #193 and arch #198 
```
# wails init
Wails v0.17.12-pre - Initialising project

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x77cdeb]

goroutine 1 [running]:
github.com/wailsapp/wails/cmd.(*Distribution).GetRelease(...)
        /wails/cmd/linuxdb.go:25
github.com/wailsapp/wails/cmd.getRequiredProgramsLinux(0x100)
        /wails/cmd/prerequisites.go:47 +0xdb
github.com/wailsapp/wails/cmd.GetRequiredPrograms(0xc000016ef8, 0x86945c, 0x1d)
        /wails/cmd/prerequisites.go:26 +0x22
github.com/wailsapp/wails/cmd.CheckDependencies(0xc000016ef8, 0xc000017101, 0xbe4ec0, 0xc0000866e0)
        /wails/cmd/system.go:249 +0xa2
github.com/wailsapp/wails/cmd.CheckDependenciesSilent(0xc000016ef8, 0x0, 0x0, 0x0)
        /wails/cmd/system.go:225 +0x2f
main.init.1.func1(0xc0000f7ea8, 0x4137e3)
        /wails/cmd/wails/2_init.go:40 +0xec
github.com/wailsapp/wails/cmd.(*Command).Run(0xc00008e580, 0xc00000e0b0, 0x0, 0x0, 0xc000081270, 0x26)
        /wails/cmd/cli.go:170 +0xd0
github.com/wailsapp/wails/cmd.(*Command).Run(0xc00008e2c0, 0xc00000e0b0, 0x1, 0x1, 0xc0000f7f78, 0x7882cf)
        /wails/cmd/cli.go:150 +0x2d5
github.com/wailsapp/wails/cmd.(*Cli).Run(0xc00000e7a0, 0x0, 0x0, 0x0, 0xc0000f7f88, 0xc00006e058)
        /wails/cmd/cli.go:47 +0x8e
main.main()
        /wails/cmd/wails/main.go:15 +0x3e
```

**Comment by bh90210** [comment]
@Vaelatern it is a known bug I am trying to find a few days now!
so until we figure it out please hold.

**Comment by Vaelatern** [comment]
I think it has to do with the old meon template not actually being overwritten.

**Comment by bh90210** [comment]
that's what I was thinking too.
the thing is that if you change fields in the yaml, for example the name it gets picked up but only for those working already, which is weird

**Comment by Vaelatern** [comment]
The list only contains:
```
debian
arch
gentoo
ubuntu
parrot
zorin
linuxmint
centos
fedora
```

**Comment by bh90210** [comment]
found it! it's sad, but it is my fault! :/ no bug..
you have to run `mewn` inside `wails/cmd` after updating the yaml. this will update the `cmd-mewn-go` and everything will work!

**Comment by Vaelatern** [comment]
Can this be a go:generate line?

**Comment by Vaelatern** [comment]
There. It works now. I checked in the mewn result in this PR.

**Comment by leaanthony** [comment]
Great work! Thanks for your time on this @Vaelatern.

**Pull request merged**
