### PR TITLE
Add Russian translation to website

### PR DESCRIPTION
**Pull request by MagicFun1241**
Based on English translation

### CODE REVIEW

**Comment by MagicFun1241** [comment]
As far as possible, I would like to help with translation of the entire site

**Comment by leaanthony** [comment]
Just need to talk with @misitebao on how we can set this up

**Comment by misitebao** [comment]
I'll finish setting up crowdin today.

**Comment by leaanthony** [comment]
Awesome. Thanks @misitebao

**Comment by MagicFun1241** [comment]
Fixed

**Review by misitebao — COMMENTED** [review]
LGTM.

**Comment by misitebao** [comment]
Please refer to "https://crowdin.com/project/wails" for contributing translation documents.

**Comment by leaanthony** [comment]
Hey @MagicFun1241 - really appreciate you doing this! We have crowdin set up now. Could you possibly do the translation via that otherwise we are in danger of losing it. Let us know if you need help with that 👍

**Pull request merged**
